opensafely-core/job-runner

- run.py
- runner/__init__.py
- runner/exceptions.py
- tests/test_runner.py
Provide specific errors for common error cases.
Where specific exceptions are not used, we return a deliberately
uninformative message, to avoid leaking potentially sensitive
Also, add a specific id to every log message associated
with a job.
> Improve errors

- Makefile
This moves the API under a `/api` prefix so the web UI can take over the un-prefixed URLs.  Pretty URLs for the humans!
It needs to be merged and deployed in conjunction with opensafely/job-server#30
> Move API Under Prefix

- jobrunner/project.py
- tests/test_project.py
This does a pure refactor to split apart loading a `project.yaml` and validating it.
As part of opensafely/job-server#61 we want to get the actions defined in a `project.yaml`.  Downloading a file from GitHub via their API gives us the file contents  so rather than saving to disk just to read it into `load_and_validate_project` it makes sense to break up those two bits of functionality.
I'm expecting to add validation to the web flow later, to add an extra layer of checks on invalid `project.yaml` reaching job-runner.
> Refactor Loading project.yaml

- jobrunner/git_askpass_access_token.py
- jobrunner/job.py
Previously we tried to redact the token from anywhere it might leak to,
but this is fiddly and error prone. Git doesn't directly support
supplying the token in an environment variable, but it does allow us to
specify a custom "askpass" executable which can grab the token from the
environment for us.
> Avoid including token in repo URL

- jobrunner/server_interaction.py
Previously we relied on `started` having been set to `False` as one of
the conditions for remaining in a `pending` meta-state.
However, this flag is set and unset by the main loop and may be in an
inconsistent state. The `status_code`, on the other hand, will remain
that of `DependencyRunning` until the related job completes, leading to
a lower likelihood of inconsistent state.
> fix: use status_code to determine something is running

- jobrunner/project.py
- tests/test_project.py
Because the arguments aren't being processed by a shell (which is good)
having a space between an `-e` and its value is not sufficient:
they must be passed as separate arguments.
> fix: Correctly separate env var arguments

- jobrunner/project.py
- tests/fixtures/invalid_project_8/project.yaml
- tests/test_project.py
This is to support CI; some analyses require larger datasets than
others to complete successfully
> feat: require project.yaml to supply expectations population

- README.md
- docker-compose.yaml
- jobrunner/job.py
Also enabled service restarts, which means the job-server become more of a
proper service in production.
PID 1 is special, and python doesn't always behave correctly as PID 1 wrt its
children. Docker includes tini, a PID 1 runner that behaves as expected and
runs your process and passes on signals and does process reaping properly.
You can use via `docker run --init` or via `init: true` in docker-compose.yaml.
Good explanation here: https://github.com/krallin/tini/issues/8
So, this enables init for job-runner, and also for jobs themselves. It may not
be related to the lock ups we've seen, but it very well could be, and it's
recommended best practise for docker daemons anyway.
> Use docker's built in PID 1 init process

- jobrunner/job.py
Quick emergency fix. Sometimes `self.workdir` is a `PosixPath`, and python does not like concatting this with a string.
> fix: don't complain on PosixPath concat

- jobrunner/utils.py
Otherwise this function doesn't work under Windows.
Fixes #60
> Use `posixpath` module in `safe_join`

- jobrunner/utils.py
Otherwise this function doesn't work under Windows.
Fixes #60
> feat: Use `posixpath` module in `safe_join` (#63)

- jobrunner/job.py
- tests/test_exceptions.py
- tests/test_job.py
- tests/test_project.py
When docker ref counts volumes asynchronously, so can some times take a short
while after a container is stopped before the volume can be deleted.
Also, renamed test exceptions in not be parsed as test cases, and fixed a dummy
filename to avoid potential clashes.
> ci: fix volume cleanup for slow docker

- jobrunner/job.py
Because we're not doing a full clone, git doesn't know what `master`
refers to when we try to checkout. But we can tell it to checkout the
commit it just fetched using `FETCH_HEAD`.
> fix: Fix two-step git checkout

- jobrunner/sync.py
This translates job-server's internal `Job.id` field _name_ to `runner_id` when talking to the API.  job-server maintains an internal primary key for Jobs, tracking the cross-system identifier in the runner_id field.
@evansd – we've used `identifier` for `JobRequest`'s cross-system ID, should we standard to that for both?  (happy to hold off on this PR to do that!)
> Translate Cross System ID Field Name

- jobrunner/sync.py
- tests/test_integration.py
This removes the `?active=true` filter since job-server only returns active `JobRequest`s.
I've also configured the API URL as part of the integration test so it's stable during test and local configuration doesn't affect it.
> Remove Active Filter

- tests/test_integration.py
The default repo for a branch can be configured globally via
init.defaultBranch.  Rather than relying on a user's default branch
matching our expectations, this uses HEAD to pick whatever is in use
locally.
Fixes #80
> Refer to default branch with HEAD

- jobrunner/job.py
- jobrunner/project.py
Previously was hardcoded to a docker.opensafely.org/job-runner.
> bug: make volume maker image configurable

- .github/workflows/tests.yml
- MANIFEST.in
We were missing the VERSION file so our wheel installed OK but the sdist didn't. I realised this when attempting to vendor the PyPI released package (which uses the sdist).
This also adds tests that the packages we build can be installed.
> Fix our sdist packaging

- jobrunner/docker.py
This was always wrong but used to work by chance when we used the
`cohortextractor` image as our volume manager because that has its
working directory set to `/workspace` anyway.
This project really needs more comprehensive tests :(
> fix: Fix reference file path

- jobrunner/project.py
Previously if `context_mark` was unset but `problem_mark` was set then
we'd never modify it, leading to error messages about an issue in
`<byte_string>` rather than an issue in `project.yaml`.
> fix: Improve YAML error messages

- jobrunner/job.py
Previously we always returned to `cohortextractor` which resulted in the
tests always appearing to pass even where there were errors.
> fix: Exit with correct status from job.py shim

- jobrunner/docker.py
- jobrunner/local_run.py
- jobrunner/log_utils.py
We don't need to see download progress in the CI logs and it means
there's mountains of output to skip through until you get to anything
interesting.
We also now log to stdout from local_run as this is where the rest of
our output goes and it leads to confusing behaviour if output is split
across two different streams.
> fix: Prevent `docker pull` from being verbose in CI

- jobrunner/database.py
- jobrunner/retry_job.py
This only applies to (and only works for) jobs which failed with an
Internal Error during the "finalise" step where we copy output files,
dump logs, update the manifest etc. When this happens we don't
automatically clean up the job's container and volume giving us an
opportunity to fix the bug and try again without having to re-run the
entire job.
> feat: Add command for retrying failed job

- jobrunner/git.py
I suddenly remembered while putting a child down for a nap that
subprocess arguments can be Path instances as well as str/bytes. Thanks
brain!
This isn't actually necessary at the moment because our `subprocess.run`
wrapper (created to work around Windows compatibility issues in Python
<3.8) converts Paths to str anyway. But hopefully we'll remove the wrapper
at some point in which case we'll need to handle Paths correctly.
> fix: Fix redaction of subprocess arguments

- jobrunner/config.py
- jobrunner/manage_jobs.py
This is a (nasty) workaround for the permissions issues we hit when
switching between running the job-runner inside Docker and running it
natively on Windows. The issue is that the Docker process creates files
which the Windows native process then doesn't have permission to delete
or replace. We work around this here by using Docker to delete the
offending files for us.
This behaviour is enabled by setting the `ENABLE_PERMISSIONS_WORKAROUND`
environment variable to a non-empty value.
Note for the potentially confused: Windows permissions work nothing like
POSIX permissions. We can create new files in directories created by
Docker, we just can't modify or delete existing files.
> fix: Work around Windows permissions issues

- jobrunner/database.py
- jobrunner/local_run.py
In the near future we plan to run the `sync` service in a thread
alongside the `run` service (for operational simplicity) and so we want
to make sure they don't attempt to share database connections.
We also make the in-memory database unique for each call to `local_run`
which simplifies testing.
> Make connection caching threadsafe

- .gitignore
- Makefile
The idea is to be able to manage a repo we can directly use as dependencies on the server, as we only have access to github.com, not pypi.org. And we possibly don't even have pip.
> ci: add tooling to build dependencies repo

- jobrunner/run.py
- jobrunner/sync.py
This catches ctrl+c to avoid exiting with a stacktrace.
> feat: exit cleanly on ctrl+c

- jobrunner/local_run.py
- jobrunner/log_utils.py
- jobrunner/models.py
- jobrunner/service.py
- tests/test_log_utils.py
Move the formatting logic into a filter rather than the formatter. This avoids
the need for parameterising the formatter, it can be customised just using a
regular format string, which I then used in the 2 places that need it
(local_run and threaded service).
Additionally, changed the log format to put various tags at the end of the
output. This pushes line noise out to the right, but still allows us to filter,
e.g:
grep project=foo log.txt | grep status=bar
> feat: refactor logging setup and formatting

- .github/workflows/tests.yml
- .gitignore
- Makefile
- jobrunner/config.py
- jobrunner/local_run.py
- jobrunner/manage_jobs.py
- tests/conftest.py
- tests/fixtures/stata_project/analysis/model.do
- tests/fixtures/stata_project/project.yaml
- tests/test_local_run.py
A stata licence can be configured by setting a STATA_LICENCE environment
variable, which will be needed for GHA and backend server usage.
For local runs, we add a best-effort convenience method - checking out a
private repo containing the opensafely license using the current user's git
credentials. If the user has access to the repo (either an opensafely member or
external collaborator), everything should just work.  If not, they'll get an
error message telling them to set the environment variable for their stata licence.
The goal of this is so we can make the stata docker image public, and avoid the
need for any alternative credentials for users - we just need GitHub.
Note: the stata-mp image does not yet require a license - that change will land
once this one has.
> feat: support external stata licence configuration

- docker-compose.yaml
- dotenv-sample
- jobrunner/config.py
- jobrunner/sync.py
Use a token in the `Authorization` HTTP header for authentication with job-server.
This is the job-runner side of opensafely/job-server#303.
> Switch to Token Auth

- jobrunner/string_utils.py
- tests/test_string_utils.py
Because we weren't doing this correctly before a project with a long
local path would end up with correspondingly long job slug e.g.
C:\Users\Dave\Documents\Foo\Bar\Baz\Blah
Would become
job-usersdavedocumentsfoobarbazblah
As log files produced during local run contain the job slug, this made
it much more likely that we would exceed Windows 260 character path name
limit.
This change doesn't fix the path limit problem, but it does mean we
probably don't need to worry about it for now.
> fix: Correctly extract project names from Windows paths

- .gitignore
- docker-compose.yaml
- dotenv-sample
- jobrunner/service.py
- scripts/install.bat
- scripts/run.sh
- tests/test_service.py
This changes the nssm config to launch a bash script that sources .env
and then execs to python.
This means we do not need to do any env parsing in python, which is
good.
Also, we drop the OPENSAFELY_ prefix used by the current .env and
docker-compose tooling, just using the actual environment variables
directly.
NOTE: the .env file in prod will need updating to remove OPENSAFELY_ prefix when this is deployed.
> fix: make windows service use a bash runner

- jobrunner/docker.py
- jobrunner/kill_job.py
- playbooks/TPP.md
It turns out we need this when certain jobs are in danger of using up
all the disk space.
> feat: Add command to kill jobs

- scripts/install.bat
- scripts/run.sh
- it no longer removes the service, as that breaks the security set up.
- explicit path for nssm
- better output, suitable for copy/pasting
- better error handling
> ci: refactor windows install script to be less shoddy

- jobrunner/local_run.py
Without this (at least on my particular Linux setup) git can't
authenticate with Github.
> fix: Pass environment through when fetching license

- jobrunner/add_job.py
- jobrunner/create_or_update_jobs.py
- jobrunner/models.py
Rather than randomly generating a job ID each time, we now use the hash
of the job request ID and the action name – which together are
guaranteed unique. This means even if we lose the entire job-runner
database while jobs are running we should be able to gracefully
recover because the same set of jobs with the same IDs should be
automatically recreated by the sync service.
Losing state like this still won't be _entirely_ unproblematic: in
particular, jobs which have already completed but are part of a job
request which is still active won't have their statuses correctly
reported. But it will at least avoid the problem of orphan jobs which
require a manual cleanup.
> fix: Generate consistent job IDs

- scripts/run.sh
This value has now been added to the environment file where it belongs.
Because the docker-compose file uses variables with an `OPENSAFELY_`
prefix we can set the config value for the native runner but not the
docker version. But it wouldn't actually be a problem to have it enabled
in both environments anyway.
> chore: Remove config value from wrapper script

- jobrunner/models.py
This copy/paste error has probably cost several weeks worth of anguished
person-time. I really am very sorry.
Closes https://github.com/opensafely/job-server/issues/335
> fix: Return correct `started_at` timestamp

- jobrunner/sync.py
We have a log line for data coming from the server, this mirrors that in an effort to debug opensafely/job-server/issues/335 (and any other maybe-sync issues!).
> Log data being sent to job-server

- jobrunner/sync.py
This adds `status_code` to the payload sent to job-server.
Refs opensafely/job-server#259
> Add Job.status_code to remote format

- jobrunner/create_or_update_jobs.py
- jobrunner/service.py
- jobrunner/sync.py
- playbooks/TPP.md
Make sure every job has an `updated_at` timestamp set (which previously it didn't in the short interval between the sync loop creating it and the run loop handling it).
Also tidying up some logging things.
> Timestamp and logging fixes

- jobrunner/project.py
- tests/test_local_run.py
Sometimes study authors want to create ancillary files alongside the
cohortextractor output. For instance, when study definitions or measures
are dynamically generated we may want to create a file recording the
parameters of the study/measure for use in later processing. Often it's
convenient to store this in a different directory from the standard
chortextractor output files.
The job-runner currently attempts to determine the expected directory
for cohortextractor output files by looking at the specified output
patterns and then appends this as an `--output-dir` argument to the
cohortextractor invocation. However if multiple output directories are
used in can't do this correctly and so throws an error.
This PR stops the error being thrown if an `--output-dir` is already
explicitly …
> fix: Allow cohortextractor output in multiple dirs

- jobrunner/manage_jobs.py
This allows analysis scripts and study definitions to customise
themselves depending on which backend they are running under. This is
absolutely not the best long term solution to the cross-backend problem
but it's a simple and relatively non-invasive solution to unblock us for
now. We're deliberately not documenting this and only using it
internally at first.
> feat: Pass `OPENSAFELY_BACKEND` env var to each job

- jobrunner/config.py
- jobrunner/manage_jobs.py
- tests/test_config.py
PRESTO_TLS_KEY_PATH and PRESTO_TLS_CERT_PATH contain paths to the
relevant files, and we load them into PRESTO_TLS_KEY and PRESTO_TLS_CERT
respectively. If present, these values are passed to the cohortextractor
invocation.
This involved some error handing with in config.py that I wanted to
test, so I wrote a stupid subprocess test harness to do so.
> feat: add PRESTO_TLS_* configs

- README.md
PyPI was 502ing on us at the point the last release was merged and due
to the current workflow setup we can't easily retry. At some point we
will definitely fix this.
> fix: Tidy up readme (to force a new release)

- jobrunner/manage_jobs.py
This is sometimes useful for debugging purposes e.g. 137 is indicative
of memory issues.
We can recover this from the Docker metadata dump in the internal log
directory but it's more convenient to have it in the user facing logs.
> fix: Include exit code in logs

- jobrunner/config.py
- jobrunner/local_run.py
- jobrunner/run.py
- tests/test_job_resource_weights.py
This gives us a very crude mechanism for controlling how many of what
type of jobs are running together.
The config file itself should be placed at `job-resource-weights.ini`
in the job-runner working directory.
It is structured as:
```ini
[some-workspace-name]
my-ram-hungry-action = 4
other-actions.* = 1.5
[other-workspace-name]
...
```
Any jobs in the specified workspace will have their action names matched
against the regex patterns specified in the config file and will be
assigned the weight of the first matching pattern. All other jobs are
assigned a weight of 1.
We also take this opportunity to randomly shuffle the jobs list before each
processing loop so as to prevent a single set of jobs hogging all available
resources.
> Support config file giving job "resource weightings"

- jobrunner/config.py
- jobrunner/docker_stats.py
- jobrunner/record_stats.py
- jobrunner/service.py
- jobrunner/system_stats.py
- tests/test_docker_stats.py
- tests/test_system_stats.py
This dumps the output of various docker and system load viewing commands as timestamped blobs of JSON in a SQLite file.
Configured using:
STATS_DATABASE_FILE
STATS_POLL_INTERVAL
Deliberately added as a new service rather than bundled up with `sync` so that we can back it out easily when we replace this with something better.
> Add crude service to log system stats to a SQLite file

- scripts/mount-job-volume.sh
It's slightly more convenient to be dumped straight into the directory
you're going to be interested in.
(Double leading slash for the benefit of git-bash.)
> chore: Set working directory to /workspace

- jobrunner/create_or_update_jobs.py
- jobrunner/database.py
- jobrunner/local_run.py
- jobrunner/manage_jobs.py
- jobrunner/models.py
- jobrunner/run.py
- jobrunner/schema.sql
- jobrunner/sync.py
- tests/fixtures/full_project/project.yaml
- tests/test_create_or_update_jobs.py
- tests/test_integration.py
- tests/test_log_utils.py
- tests/test_sync.py
The UI for this has already been added but only enabled for admin users:
opensafely-core/job-server#382
This requires a database migration which needs to be done by hand for now:
1. Stop the runner and update:
```sh
/c/nssm-2.24/win64/nssm stop opensafely
git pull
```
2. Open a python shell:
```sh
bash scripts/run.sh
```
3. Add the column:
```py
from jobrunner.database import get_connection
get_connection().execute("ALTER TABLE job ADD cancelled BOOLEAN")
```
1. Restart the runner:
```sh
/c/nssm-2.24/win64/nssm start opensafely
```
> Support cancelling jobs on user request

- jobrunner/run.py
It turns out there are two seperate paths a failed job can go through
depending on exactly how it failed. This is because the once simple code
has splurged slightly and needs a bit of refactoring. Shouldn't be a
huge job but don't want to do it right now.
> fix: Fix logging and status messages for job cancellation

- jobrunner/local_run.py
You might now be running `opensafely pull` when you get this message,
rather than `opensafely run`.
Anality level: +100
> fix: Tweak error message now it's used in multiple contexts

- jobrunner/manage_jobs.py
- setup.py
- tests/test_local_run.py
Previously, if the case of an output file changed we would end up
deleting it every time we copied it out :(
The WindowsPath object already contains some case-normalisation logic
for comparison/hashing, but we also need to run correctly on macOS we is
case-insensitive but uses PosixPath. Doing the comparisons directly with
inodes is a bit of blunt tool but should give us the correct behaviour
here.
> fix: Safely handle case-insensitive filesystems

- .gitignore
- jobrunner/local_run.py
Update the help text for the --force-run-dependencies argument. This commit is in addition to opensafely/documentation#217, which updates the documentation.
> docs: Update the help text

- jobrunner/add_job.py
- jobrunner/config.py
- jobrunner/create_or_update_jobs.py
- jobrunner/git.py
- tests/test_create_or_update_jobs.py
- tests/test_git.py
- tests/test_integration.py
- tests/test_manage_jobs.py
This is already enforced by the job-server but this means that even if
job-server is compromised it's impossible to run code unless you have
commit access to an OpenSAFELY repo.
> Validate that commits belong to OpenSAEFLY repos

- jobrunner/run.py
I think I originally didn't do this to aid debugging. However, it leads
to a cascading failure state where a job fails to start because Docker
runs out of disk space while copying in input files, and then the volume
never gets cleaned up and we can't even extract outputs from completed
jobs to free up space because we can't start the container required to
do the copying.
The one case now when we still *don't* automatically clean up is when a
job completes but hits some unexpected internal error while finalising.
In this case it seems premature to discard the results of potentially
long-running job when often the condition is fixable and the
finalisation step can be successfully retried later.
> fix: Clean up jobs which fail to start correctly

- .github/workflows/tests.yml
This broke recently, presumably due to an upgrade to pip.
> ci: Fix packaging test

- Makefile
- jobrunner/config.py
- jobrunner/git.py
This will allow us to drop github access for job-runner.
Note: I verified the changed code is under tests, as tests fail if I break it
deliberately. But there's no easy way to test this change in isolation,
so have relied on current test paths.
> feat: use the github proxy to clone study repos

- jobrunner/git.py
- jobrunner/local_run.py
- tests/test_git.py
- tests/test_local_run.py
This PR contains two changes: one to ensure that our use of git-fetch is atomic and prevent the problems caused by partially fetched commits; and another to expand the class of errors on which we automatically retry fetches.
> Attempt to fix git reliability issues

- .github/workflows/tests.yml
- jobrunner/git.py
- tests/test_git.py
After all the bikeshedding over configuration I missed the fact that
there's another function which talks to Github which didn't have the
proxy transformation applied! By moving this in with the auth stuff it's
now impossible to accidentally miss this.
> fix: Apply github proxy when resolving remote refs

- .github/workflows/tests.yml
- jobrunner/local_run.py
Github Actions supports various [magic strings][1] for formatting
output. In particular, it allows you to hide output behind an expandable
toggle. We exploit this to embed the full log file from each action run
in the test output. We also add some very basic text formatting to
improve readability of the test output.
Example of collapsed output:
Example of expanded output:
Addresses https://github.com/opensafely-core/research-action/issues/6
[1]: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#grouping-log-lines
> Include full log files in Github Actions output

- .github/workflows/build_and_publish.yaml
We haven't renamed the default branch yet, but we want to make sure this
keeps working when we do.
> chore: Support master and main as release branches

- tests/test_create_or_update_jobs.py
- tests/test_git.py
Previously we used the documentation repo but, as was totally
predictable, some changes in the recent tidy up broke these tests. We
now use a dedicated test repo.
> chore: Use dedicated test repos on Github

- jobrunner/run.py
Rather than marking jobs as running and then waiting for the next loop
iteration to actually cancel them, we now immediately invoke
`handle_running_job` to do the cancellation. This gives us the same
structural advantages as we had previously, but it makes cancellation
faster and means we no longer misleadingly report cancelled jobs as
having a non-zero runtime.
> fix: Slightly better behaviour for cancelled jobs

- jobrunner/project.py
- tests/fixtures/full_project/analysis/count_lines.py
- tests/fixtures/full_project/project.yaml
- tests/test_integration.py
For commands that require complex config, users can supply a config key in
project.yaml.  We serialize this as JSON, and pass it to the command with the
--config flag.
Fixes #225
> feat: Support passing complex config from project.yaml to commands

- tests/test_manage_jobs.py
Previously, we tested the operating system for case sensitivity. However, this fails on some macOS installs because whilst macOS is POSIX-compatible, by default APFS (Apple File System) is case insensitive. Python's standard library doesn't have a function for testing the filesystem; seemingly the best way is to write/read a temporary file. Finally, because this function is specific to the test, rather than the application code, it's next to the test.
> Test filesystem for case sensitivity

- jobrunner/config.py
- jobrunner/create_or_update_jobs.py
- jobrunner/local_run.py
- jobrunner/manage_jobs.py
- jobrunner/project.py
- tests/test_manage_jobs.py
- tests/test_project.py
Reusable Actions, Part Deux 🎉 
The best place to start is *jobrunner/project.py*. Here, `handle_reusable_action` rewrites actions that resolve to reusable actions. It's called within job-runner's sync loop, before a transaction is opened on the database.
A small change within *jobrunner/manage_jobs.py* to `create_and_populate_volume` ensures that reusable actions are handled correctly within job-runner's run loop.
Next steps...
This PR follows #232, which was closed after much squashing and force pushing.
> feat: Handle reusable actions

- jobrunner/config.py
- jobrunner/local_run.py
- jobrunner/run.py
- tests/test_integration.py
The addition of the `generate_cohort_with_dummy_data` action made the dependency graph no longer have a single root. Combined with the job order randomisation that we apply this made it non-deterministic which job was started first which made the test intermittently fail.
This PR disables job order randomisation during the test and slightly refactors how the behaviour of the main `run` loop is configured.
It also re-organises the test to restore the single graph root and hopefully make things clearer.
> fix: Fix non-deterministic integration test

- jobrunner/create_or_update_jobs.py
- jobrunner/github_validators.py
- jobrunner/project.py
- tests/test_project.py
This ensures that reusable actions have valid images names, and also prohibits them from invoking data extracts. In theory we could allow these, but we know of no valid use case for that at present and limiting the powers of reusable actions seems sensible.
This PR also moves some common validation code into its own module to avoid circular import problems, and splits out the git-related and non-git-related parts of the "handle" function so we can test independently without needing to mock.
> Validate image names for reusable actions

- jobrunner/git.py
- tests/test_git.py
Previously, if `get_sha_from_remote_ref` was passed a ref that resolved to [an annotated tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging), then it would return the SHA of the annotated tag and not of the associated commit. This was a pain, because we tend to assume that SHAs are commit SHAs and not tag SHAs; for example, when checking that a branch ref is an ancestor of a commit ref.
This PR ensures that if `get_sha_from_remote_ref` is passed a ref that resolves to an annotated tag, then it returns the SHA of the associated commit.
> Dereference annotated tags

- jobrunner/local_run.py
Previously, we made temporary directories inside the project root. As project root directories are often already quite deeply nested this meant the paths to the temporary directories were quite long. When combined with the fact that the log files we create inside these temporary directories often have long names themselves this would sometimes result in us exceeding the Windows 260 character path length limit. This lead to very confusing error conditions for researchers.
Using the system tempdir sidesteps this problem, and is generally neater.
We also switch to using a persistent rather than throwaway directory within the system tempdir for reusable action git repos. This means we don't have to keep refetching commits and also avoids the complexity of deleting git's read-only directories …
> Use system tempdir when running locally

- jobrunner/project.py
This was its previous behaviour. Most of the time we don't care about
the version and so it's cleaner if we can just ignore it.
> fix: Make `is_generate_cohort_command` return bool

- .github/workflows/tests.yml
- jobrunner/local_run.py
- tests/test_local_run.py
Get rid of the "temporary workaround" function, enforce the presence of the license and ensure we test it properly in CI.
> Clean up Stata cruft

- jobrunner/create_or_update_jobs.py
- jobrunner/project.py
- jobrunner/sync.py
- tests/test_create_or_update_jobs.py
- tests/test_integration.py
- tests/test_sync.py
This refactors the job creation and dependency resolution logic so it is no longer intertwined with database access and so it no longer needs to run within a transaction. As well as making the code clearer (I think) this means we can now do expensive operations like pulling from Docker or fetching from Github after we've worked out what we're going to run but before we written anything to the database or opened a transaction.
> Refactor job creation to remove db access

- jobrunner/create_or_update_jobs.py
- jobrunner/manage_jobs.py
- jobrunner/models.py
- jobrunner/schema.sql
- tests/test_manage_jobs.py
THIS REQUIRES A DATABASE MIGRATION, SO ANY DEPLOY NEEDS BABYSITTING.
There are no existing tests for what gets logged and stored in manifest.json, so I haven't added any new tests here.
Fixes #236.
> Record reusable actions in manifest

- jobrunner/create_or_update_jobs.py
- jobrunner/manage_jobs.py
- tests/test_create_or_update_jobs.py
- tests/test_service.py
This refactors the job creation process to do all disk access upfront in
a single batch, as we now already do for database access.
This means that the bulk of the job creation logic is now in a pure
function which takes a list of current jobs and returns a list of new
jobs.
As well as being a general structural improvement this paves the way for
support something other than local disk as the primary data store.
> Further refactoring of `create_job`

- .github/workflows/tests.yml
This isn't required for running locally but it is required for packaging
correctly. This PR also adds a basic smoke test that should have
caught this kind of issue.
> Add missing `__init__.py` file

- jobrunner/cli/local_run.py
- jobrunner/config.py
- jobrunner/create_or_update_jobs.py
- jobrunner/manage_jobs.py
- jobrunner/models.py
- tests/test_manage_jobs.py
Rather than having production and local_run share a single codepath peppered with switches on `config.LOCAL_RUN_MODE` we provide a separate `create_jobs` implementation for local_run, and use common functions to share common behaviour.
This simplifies the code overall, and makes it easier to further customise behaviour between the two execution modes (e.g. to support automatically pulling new docker images in production, but only warning about available updates in local_run).
> Remove need for LOCAL_RUN_MODE flag

- jobrunner/lib/docker.py
Large files may legimately take a long time to copy.  We had already
removed this from copies _into_ the volume but neglected to do it for
copies out.
> fix: Remove default timeout for copies out of Docker volume

- jobrunner/manage_jobs.py
- jobrunner/run.py
Containers which get themselves into this frozen/broken state can't be
cleaned up because any attempt to interact with them hangs indefinitely.
We used not to try, but we've since changed the cleanup logic due to
disk space issues so we now need an explicit guard to prevent the
cleanup (this is better practice anyway).
On the upside, we haven't noticed this bug because we haven't hit the
frozen container issue in quite a while!
> fix: Fix handling for "frozen" containers

- jobrunner/config.py
- jobrunner/job_executor.py
- jobrunner/run.py
- tests/factories.py
- tests/test_run.py
Inital implementation of the spike API
This adds an EXECUTION_API feature flag, which switches the main run
loop to us alternate version of `handle_pending_jobs` and
`handle_running_jobs`, which use the API.
It adds unit tests for those new functions, using the fact we now have
an API! Fairly basic branch coverage to start with, but more to add.
Things this branch does not do:
- implement selection and loading of the API implementation
- handle manifest state
The spike code is mostly unaltered, except for moving the `set_message`
into `sync_job_status`, and adding an additional `update(job)` call.
> feat: initial api support

- README.md
e.g. `HIGH_PRIVACY_STORAGE_BASE` seems to be the thing used everywhere
> feat: amend environment variable names in documentation

- jobrunner/manage_jobs.py
At the moment, cancelled jobs are treated like failed jobs with the
consequence that they end up removing previous outputs from the same
action. We want them to act like jobs which were never really run.
However, for debugging purposes we still want to keep their logs and
metadata around. We do this by "part finalizing" them. This is not a
nice way of doing this, but this issue needs fixing now.
Fixes #246
> fix: Cancelled jobs should not modify workspace

- jobrunner/job_executor.py
- jobrunner/run.py
- tests/factories.py
- tests/test_integration.py
- tests/test_run.py
Split the `JobAPI.run()` into separate prepare/execute/finalize steps.
This also makes JobAPI properly async, and splits out the state it's tracking into a separate ExecutorState.
This simplifies and changes a lot of things, so the main loop for the API is quite different from the the current one, so we diverge and split a function call higher up than previously.
> feat: refactor JobAPI.run() into separate preprare/execute/finalize stages

- jobrunner/lib/git.py
- tests/lib/test_git.py
We attempt to distingish between "this repo does not exist" and "this
ref does not exist" so we can provide more helpful error messages.
Unfortunately our use of the [--exit-code][1] flag on `ls-remote` made
this not work as intended. This PR fixes this and adds tests for this
behaviour.
Closes #306
[1]: https://git-scm.com/docs/git-ls-remote#Documentation/git-ls-remote.txt---exit-code
> fix: Raise correct errors from `get_sha_from_remote_ref`

- jobrunner/cli/local_run.py
- jobrunner/config.py
- jobrunner/lib/git.py
- tests/lib/test_git.py
This PR changes the local_run config to access Github directly rather than pushing traffic through the proxy which is unnecessary here.
It also prevents git from prompting for credentials which it will do whenever an action repo is mistyped (Github treats all missing repo errors as authentication failures to avoid leaking the existence of private repos).
> Fixes for accessing GitHub when running locally

- jobrunner/cli/local_run.py
- jobrunner/lib/log_utils.py
- tests/cli/test_local_run.py
- tests/lib/test_log_utils.py
For debugging purposes, we log some categories of caught exceptions. This is useful in production, but it's not helpful when running locally and creates confusing noise for the user. For example, trying to run a non-existent reusable action currently gives output like this:
```
$ opensafely run my_action
Error reading from remote repository
Traceback (most recent call last):
File "/home/dave/projects/ebmdatalab/job-runner/jobrunner/lib/git.py", line 139, in get_sha_from_remote_ref
response = subprocess_run(
File "/home/dave/projects/ebmdatalab/job-runner/jobrunner/lib/subprocess_utils.py", line 19, in subprocess_run
return subprocess.run(cmd_args, **kwargs)
File "/usr/lib/python3.8/subprocess.py", line 516, in run
raise CalledProcessError(retcode, process.args, …
```
> Hide logged exceptions in local run

- .github/workflows/build_and_publish.yaml
- .github/workflows/tests.yml
- .gitignore
- DEVELOPERS.md
- docker/Dockerfile
- docker/Makefile
- docker/docker-compose.yaml
Using SSH by default was slower, and error prone on different
developer's environments (e.g. they had to have SSH set up).
Instead, we default matching the docker GIDs so we can mount the socket.
This avoids the need for SSH in prod and dev
SSH is still supported however, as it is possibly useful in prod in the
longer term.
> ci: fix local docker dev setup to not use SSH.

- jobrunner/run.py
- tests/test_run.py
Somehow this was overlooked in the executor API work. It was there at
one point, as the removal of `handle_active_jobs_api` shows, but in the
refactoring of the active job loop must have got lost, and the tests
were missing.
Most of the diff is the indention of the unalterd main job handling code to be wrapped in try: except
> fix: mark jobs as failed on error with executor api

- scripts/watch-job-logs.sh
The new "local Docker" job executor sets a different label from the old
code.
> fix: Update docker label to match new value

- jobrunner/lib/docker.py
The errors in production had a `.` on the end of the message, meaning
the endswith clause was not an exact match.
> fix: fix disk space error detection

- .pre-commit-config.yaml
* Match the versions in the requirements.
* Switch deprecated `mirrors-isort` to `isort`.
* Change PyCQA GitLab to GitHub.
* Remove deprecated `seed-isort-config` (it's archived and not needed for
isort versions).
> chore: Update `.pre-commit-config.yaml`

- jobrunner/config.py
- jobrunner/project.py
- jobrunner/reusable_actions.py
- tests/test_project.py
This image is the same as the `cohortextractor-v2` image with a different name.
Eventually we could clean up and remove support for the `cohortextractor-v2` image. That would be once any study/test code using that image is migrated to the databuilder image.
> chore: Support databuilder Docker image

- jobrunner/cli/local_run.py
If `getpass.getuser()` can't find the current username from the
environment it falls back to importing `pwd`, which doesn't exist on
Windows. In addition it may fail in various other ways. See:
https://bugs.python.org/issue32731
Knowing the current username isn't crticial so we shouldn't fail if this
happens, just set the username to "unknown".
> fix: Be robust against `getuser()` failing on Windows

- jobrunner/project.py
We renamed `generate_cohort` to `generate_dataset` in opensafely-core/databuilder#383, this special cases that command in job-runner.
> fix: handle databuilder's generate_dataset command

- docker/Dockerfile
The volume mounts were originally added as metadata, but it turns out if
you don't supply a mount, docker creates one for you with the contents
of that dir in your that lasts beyond the containers lifetime and eats
disk.
> fix: remove volumes from docker images

- .github/workflows/tests.yml
- jobrunner/run.py
- tests/cli/test_local_run.py
- tests/fixtures/full_project/analysis/count_by_year.py
- tests/fixtures/full_project/analysis/dataset_definition.py
- tests/fixtures/full_project/analysis/dummy_action.py
- tests/fixtures/full_project/project.yaml
- tests/fixtures/full_project/test-data/databuilder-dummy-data.csv
- tests/test_integration.py
- tests/test_reusable_actions.py
This adds databuilder to a handful of job-runner's tests where we're using cohortextractor as a meaningful part of the test.  A few of these changes are a little messier than I'd like (the integration ones in particular), because databuilder doesn't support the columns we need to match cohortextractor.  I've made these changes on the presumption that we'll update these tests as we add those columns to databuilder.
> Test with Data Builder

- jobrunner/executors/local.py
- jobrunner/manage_jobs.py
- scripts/archive.sh
- scripts/test_archive.sh
- scripts/unarchive.sh
- tests/test_local_executor.py
- simple initial archive/unarchive scripts
- local executor detects archived workspace and errors with message
> feat: handle workspace archiving

- .github/workflows/tests.yml
This bumps our use of actions/checkout from v1 to v3.  There have been many changes in the action since v1, most notably for us is the setting of the AUTHORIZATION header to force basic auth with the GITHUB_TOKEN which I've disabled in the `get_sha_from_remote_ref` function.
> Bump actions checkout v3

- jobrunner/executors/local.py
- jobrunner/lib/__init__.py
- jobrunner/lib/docker.py
- jobrunner/manage_jobs.py
- tests/lib/test_init.py
We previously changed `docker.copy_from_volume()` to write to
a temporary file and rename, to gain basic atomic write behaviour.
This change generalises this and extends it to the non-docker
`copy_file()` method.
It also means we do not follow symlinks when writing to a file, as
`shutil.copy()` and friends do. This is useful in migrating between file
systems
> fix: atomic file writing and not following symlinks

- jobrunner/cli/prepare_for_reboot.py
- playbooks/tpp-backend.md
We're going to be rebooting a few times in the coming days and it's
better if this can be mostly transparent to users.
> feat: Add `prepare_for_reboot` command

- jobrunner/lib/docker.py
- justfile
- tests/lib/test_docker.py
Somehow this was missed in the pre-migration testing.
This fix has been cowboy'd in TPP, so this is adding it properly
> fix: follow symlinks when copying to volume

- setup.py
#351 added `__init__.py` files to all the tests directories, turning them into packages which `find_packages()` subsequently found.  However, we don't want that so this exludes said `tests` package.
> fix: exclude tests from package artefacts

- .github/workflows/build_and_publish.yaml
- .github/workflows/tests.yml
- .gitignore
- setup.py
This switches us from invoking setup.py directly to using the `build` tool, as documented in the [packaging guide](https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives).
In trying to remove tests (#381 didn't work) I found that `python setup.py bdist_wheel` was including tests regardless of whether I [directly set `packages=["jobrunner"]`](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use) or various combinations of [`where`, `include`, and `exclude`](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#automatic-package-discovery).
Since `build` is now the documented tool and does the right thing this moves us to using it.
> Build Distributions with `build`

- .github/workflows/build_and_publish.yaml
- .github/workflows/tests.yml
- justfile
- setup.py
This improves our packaging story by doing a number of things:
* test the installed package via one of its entrypoints to avoid python -m using the code on-disk
* exclude tests _and_ its sub modules
* check the build distribution doesn't include tests by interrogating the built wheel
* pull the building and testing of distributions into the justfile for easier local testing
> fix: correctly exclude tests from package

- jobrunner/run.py
As the comments say, this is a bit of a quick and dirty fix. We still
need to get to the bottom of what's causing these timeouts.
> fix: Prevent Docker timeouts from marking jobs as failed

- jobrunner/lib/docker.py
- jobrunner/run.py
We saw some timeouts in TPP which were caused by trying to stream very
large log files over docker.
This change puts an upper bound of 100k lines on job logs, and removes
the previous retry-on-docker-timeout attempt to fix this issue.
> fix: limit docker log size and remove previous quickfix

- jobrunner/config.py
- jobrunner/executors/local.py
- tests/test_local_executor.py
cohortextractor now exits with custom exit codes for database errors - see https://github.com/opensafely-core/cohort-extractor/pull/791
This PR is just to report user-friendly error messages when job-runner encounters those exit codes
Fixes #184
> feat: Return custom messages for known db exit codes

- jobrunner/run.py
This should hopefully save stress for users and reduce the number of
messages to tech-support.
> fix: Add explanatory text to Internal Error messages

- jobrunner/config.py
- jobrunner/executors/local.py
- jobrunner/job_executor.py
- jobrunner/lib/docker.py
- jobrunner/run.py
- tests/test_local_executor.py
- tests/test_run.py
The default limits are provided by env var config, and are set
deliberately low, but enough that they shouldn't affect `local_run`.
Actual backends would have higher defaults.
It adds the settings into JobDefinition, so that other executors can use
them. Also, we anticipate these limits being able to be included in the
JobRequest from job-server in the future.
> feat: limit job cpu/memory usage by default.

- jobrunner/queries.py
- jobrunner/run.py
- tests/test_queries.py
- tests/test_run.py
Setting mode flag to pause* will stop new jobs from starting. It does
not affect jobs that are already running.
This is designed to allow use to drain the queue of a jobs a bit before
a reboot or other maintenance. It was pleasantly simple to implement.
*`python3 -m jobrunner.cli.flags set mode=pause`
> feat: add pause mode

- jobrunner/config.py
- jobrunner/executors/local.py
- tests/test_local_executor.py
Previously, the message lists both causes as possible, which actually was more
confusing tothe user, as they didn't know which it was.
This detects when the jobs has been killed by the OOM killer, and provides
useful feedback.
> fix: differentiate 137 exit codes between OOM and admin.

- jobrunner/executors/local.py
Previously I thought the "local" executor was used to run actions locally via opensafely-cli, so it might be useful to log that.  Since it's actually how jobs are run on the server too, it doesn't serve any useful purpose to log and could be confusing.
> fix: Remove pointless local_run metadata and log

- jobrunner/config.py
- jobrunner/executors/local.py
- jobrunner/manage_jobs.py
It was only needed for runing on windows in production, and we're
running on linux now.
> chore: remove ensure_overwritable

- jobrunner/cli/flags.py
- jobrunner/models.py
- jobrunner/queries.py
- jobrunner/run.py
- jobrunner/service.py
- jobrunner/sync.py
- requirements.dev.in
- requirements.dev.txt
- tests/cli/test_flags.py
- tests/test_queries.py
Record when a flag was last set or unset. This will be helpful in
diagnosing issues, as it can help us see when things changed.
This did involve adding a new column to the Flag table, which we've not
got a mechanism to handle. But errors with the flag table are gracefully
handled, and its a simple manual ALTER TABLE to run on TPP (the only
place that currently has the flag table).
> fix: record timestamp for flag changes

- jobrunner/executors/local.py
- jobrunner/job_executor.py
- jobrunner/lib/docker.py
- jobrunner/run.py
- tests/factories.py
- tests/test_local_executor.py
- tests/test_run.py
Previously, we had punted on collecting unmatched outputs when writing
the local executor, so this was missing from that code path.
In deleting the old code path, that functionality was lost.
This change adds it to the local executor flow. It seemed fairly simple
in the end, not sure why we did not do it the first time round.
There were not tests previously for this, so I added some. In doing so,
it seems the file timestamp logic had a bug, as `docker cp` seems to
preserve the timestamp of the src file, rather than update it on the dst. So
I changed to actually `touch` a new file rather than a copy.
The tests also exposed that docker's filesystem only supports 1s
precision on file timestamps, so the test had to sleep for 1 second.
> fix: record unmatched outputs in local executor

- .gitignore
- justfile
It was bitrotten with the move to justile. Used it to add update the
dependencies branch.
> chore: fix the update-wheels command

- jobrunner/executors/local.py
- tests/test_local_executor.py
The `g` format specifier unhelpfully switches to scientific notation for
numbers above 10.
> fix: the limit formatting in OOM error message

- jobrunner/sync.py
- requirements.dev.in
- requirements.dev.txt
- tests/test_sync.py
We now support a `mode` flag and a `pause`, as the two are independantly
enabled.
This change communicates all currently set flags to job-server, rather
than just the 'mode' flag.
> fix: send all current flag values to job-server

- jobrunner/executors/local.py
- jobrunner/executors/volumes.py
- tests/test_local_executor.py
This is introduces a `volume_api` interface, in order to be able to
support different docker volume implmentations.
The only implementation is the current docker volume one, and it simply
wraps the various functions that were previously used. It does however
change the api to take a `job`, in order to:
a) make the the volume name opaque to the executor, in order that it can
be a named volume or a host path.
b) `job` has all the information needed various volume api fuctions to
work.
Doing this refactor has highlighted that the current implementation
places the responsibility of figuring out outputs and error on the
executor, when really this should be shared logic. Have written this up
as #425
This is related to fixing #407
> chore: refactor local volume management

- docker/Makefile
- docker/docker-compose.yaml
- jobrunner/config.py
- jobrunner/executors/local.py
- jobrunner/executors/volumes.py
- tests/conftest.py
- tests/test_local_executor.py
This volume api implementation uses host directories and bind
mounts them into the docker container.
This approach sould be more efficient than the docker
volume api, which has to `docker cp` everything onto the volume. This
can just fast local filesystem copy, using `os.sendfile` on linux.
This is tested on linux only, and had to be explicitly enabled via
config, and is indended to be used in production backends.
> feat: add a bind mount volume api

- jobrunner/actions.py
- jobrunner/lib/path_utils.py
- tests/lib/test_path_utils.py
When jobrunner parses the pipeline config on windows, dummy_data_file is
a windows path with \ in. When passed verbatim to docker, this blows up.
So we ensure we convert it to unix path at this point
> fix: ensure paths passed to docker are unix paths

- jobrunner/run.py
- tests/factories.py
- tests/test_run.py
In our local docker implementation, this can't happen, as all
transitions to an ERROR state are driven synchronously by the main loop
calling the API.
However, in the Graphnet K8S environment, this happens asynchronously,
so the state of the job can be in ERROR at any point.
This change handles it being in the ERROR state before we even try to
transition it, which is the correct thing to do.
I had to tweak the StubExecutorAPI handle setting a message initially.
Fixes #440
> fix: handling initial executor state being ERROR

- docker/Dockerfile
- docker/docker-compose.yaml
- docker/justfile
Running as non-root user by default was causing issues for graphnet, and
making it difficult to deploy to TPP, so regress to run running as root
for now.
Also, renamed the user inside the container as `opensafely` rather than
app users.
We still run as this user in local docker dev env, or else file
permissions get messy. But we do that in the docker-compose.yaml rather
than hardcoding in the dockerfile
> fix: move docker image to run as root in prod

- DEVELOPERS.md
- jobrunner/actions.py
- jobrunner/config.py
- jobrunner/extractors.py
- jobrunner/lib/commands.py
- tests/lib/test_commands.py
- tests/test_actions.py
- tests/test_extractors.py
See #448 (will also need an update to the vendored jobrunner in opensafely-cli once this PR is merged)
> fix: Remove support for cohortextractor-v2

- pyproject.toml
- requirements.prod.txt
Related to #448, opensafely-pipeline has now removed support for cohortextractor-v2 also
> fix: Bump opensafely-pipeline to v0.2.0

- DEVELOPERS.md
- jobrunner/cli/local_run.py
- jobrunner/cli/migrate.py
- jobrunner/lib/database.py
- jobrunner/service.py
- pyproject.toml
- tests/cli/test_local_run.py
- tests/conftest.py
- tests/lib/test_database.py
- tests/test_service.py
We have some pending db changes to make. In preparation for this, this
change adds a formal migration system to the micro-ORM.
* To avoid having to package raw sql files, we track the migrations as
string literals in python code, as dict mapping version to SQL
string.
* We use the `PRAGMA user_version` db variable to track the migration
version, using transactions to ensure it is set appropriately.
* We add a migrate command, analagous to django `manage.py migrate`.
This will ensure a db exists and is at the latest schema version.
This is the only way to create/migrate a db, and should be run as an
explicit step as part of production deployments
* Previously, in production schema creation happened lazily when the
service started up. Extending this to apply migrations automatically
on …
> feat: add schema migrations framework

- jobrunner/config.py
- jobrunner/lib/commands.py
- tests/lib/test_commands.py
As well as adding sqlrunner's image to the list of allowed images, we also let job-runner know that sqlrunner's image requires DB access. We modify `requires_db_access` slightly, because unlike the other images that require DB access, we don't invoke sqlrunner's image with a (sub)command.
See also opensafely-core/sqlrunner#15 for building and publishing sqlrunner's image.
> Make job-runner aware of sqlrunner

- jobrunner/cli/migrate.py
- jobrunner/lib/database.py
- tests/lib/test_database.py
Some issues when testing the new migration code with an actual
migration.
- ensure migrations are imported, as they are defined in code.
- add verbose flag to ensure_db/migrate_db. This is only turned on when
running via the cli command - we do not want opensafely cli users to
be bothered with it
> fix: fix migrate command and improve migration logging

- jobrunner/lib/log_utils.py
- jobrunner/models.py
- tests/lib/test_log_utils.py
Jobrunner's user of project pre-dates jobserver's Project concept, so
rename these in model and logs to workspace
> fix: rename project to workspace

- jobrunner/create_or_update_jobs.py
- jobrunner/models.py
- jobrunner/run.py
- tests/factories.py
- tests/test_run.py
This means the a StatusCode is always required, and function signatures
have changed as a result.
Also, I noticed that that a few of our failure cases were being handled
in the handle_job(n) method, when really they should have been handled
by the generic exception handler to unify process, so fixed that in the
process.
> feat: add fine grained status codes and track them in the db.

- jobrunner/cli/local_run.py
- jobrunner/create_or_update_jobs.py
- jobrunner/models.py
- jobrunner/run.py
- jobrunner/service.py
- jobrunner/tracing.py
- pyproject.toml
- requirements.prod.txt
- tests/conftest.py
- tests/factories.py
- tests/test_create_or_update_jobs.py
- tests/test_integration.py
- tests/test_run.py
- tests/test_sync.py
- tests/test_tracing.py
This adds opentelemetry tracing to running jobs.
A new jobrunner/tracing.py module handles most of the work, and we use
it to trace state changes between the fine grained StatusCode states
added previously.  We store as many attributes on each span as possible.
This includes a migration to add somewhere to store a job's trace
context and last changed timestamp.
We also emit "marker spans" that indicate that a the job has entered
a certain state, but not yet exited it yet. This is intedended to be
useful for ongoing jobs.
Also, we add a final "RUN" span once the job has completed that serves
as coarser grained span to use for graphing whole job metics.
> feat: add opentelemetry tracing

- jobrunner/tracing.py
- tests/test_tracing.py
When we switch over to the new code, we'll encounter jobs that began
under the old code, so just ignore them rather than blowing up.
> fix: handle uninitialized traces gracefully

- jobrunner/cli/prepare_for_reboot.py
- jobrunner/models.py
- tests/cli/test_prepare_for_reboot.py
- a new status code WAITING_ON_REBOOT
- properly using the volume_api to remove volmes rather than assuming
docker volumes.
- add a test for prepare_to_reboot to make sure it works going forward
> fix: update prepare_for_reboot to handle tracing

- jobrunner/create_or_update_jobs.py
- jobrunner/tracing.py
- tests/factories.py
- tests/test_create_or_update_jobs.py
- tests/test_tracing.py
Sometimes job requests can fail before they even get to creating jobs.
The initial tracing code didn't handle this properly, and this change
fixes that so that it such errors are traced properly
> fix: proper tracing for job request internal errors

- jobrunner/run.py
- tests/test_run.py
- tests/test_tracing.py
Previously, spans for a NONZERO_EXIT had not been properly marked as an
error in the span due to this bug.
> fix: fix span error handling for failed job

- jobrunner/tracing.py
- tests/test_tracing.py
By passing ctx into the root span creation, we accidentally made the
span it's own parent.
Also added missing test coverage, which found a bug and acts as
a regression test
> fix: fix span parent.

- jobrunner/executors/local.py
- jobrunner/executors/logging.py
- jobrunner/run.py
- tests/factories.py
- tests/test_run.py
The job loop assumes all operations are async. But for the local
executor this isn't true - both `prepare()` and `finalize()` are
synchronous.
This leads head-of-line blocking when a new job request arrives, in that
all jobs that can run are synchronously prepared in one pass of the
loop. This blocks those jobs from executing until the loop goes round
again, which can be a long time (e.g 30+mins), as the file copying for
n jobs can take a while.
This change allows an executor to declare it has certain transitions
that are synchronous, and if the loop detects this, it will immeadiately
run the the handler function again to move it to the next state.
For the local executor, we declare that both PREPARING and FINALIZING
are synchronous.
> fix: optimise loop for synchronous prepare/finalize

- jobrunner/create_or_update_jobs.py
- jobrunner/lib/log_utils.py
- jobrunner/run.py
- jobrunner/tracing.py
- tests/test_create_or_update_jobs.py
- tests/test_tracing.py
The previous commit added some span attribute clean up, and logged when
there were invalid attributes.
This change used that logging to find and fixa few issues:
- job.commit is None in local_run, so only add if its set
- job.message is None initially - change it to always be set.
- the `mark_job_as_failed()` function had the wrong signature for
attrs, and was adding a `attrs=None` attribute.
Additionally, lowered the tracing logging level, and quitened it for
local_run, as we don't want to bother the user with non-fatal tracing
errors.
> fix: handles some bad span attributes and logging

- jobrunner/cli/kill_job.py
- jobrunner/executors/logging.py
- jobrunner/models.py
- jobrunner/run.py
- tests/test_run.py
Previously, the user had to pass error=True (or error=exc) to get this.
To fix this, we make two changes
a) mark_job_as_failed require an explicit 'message'.
b) if `error` isn't explicity passed in, mark it as error anyway
Also, we fix up KILLED_BY_ADMIN
Fixes #497
> fix: ensure mark_job_as_failed always marks trace as error

- docker/docker-compose.yaml
- justfile
- pyproject.toml
This will cause the tests to fail if the code coverage is under this percentage. It's initially been set to match the existing coverage amount, although the hope is that this will increase over time.
Coverage is only run when running `just test` or `just docker/test`. This is because other `just test*` options only run a subset of the tests, so we can't get a useful result from the coverage tool. However, since `just docker/test` is run in CI, it will always run for every code change.
> Set test coverage target

- jobrunner/create_or_update_jobs.py
- jobrunner/run.py
- tests/test_create_or_update_jobs.py
For jobs that have completed but failed in some way, and also for jobs
that failed before they've even started, make them as errors in trace
data and ensure theres exception data
> fix: fix some trace error handling

- .gitignore
- pyproject.toml
- tests/lib/test_path_utils.py
By default (according to --help as of v22.8.0) black is already ignoring this list of directories:
/(\.direnv|\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|venv|\.svn|_build|buck-out|build|dist|__pypackages__)/
We were using --exclude which overwrote this list.  Black supports --extend-exclude which builds upon this list and also makes use of the repos .gitignore [1].  Since we we want both git and black to ignore the files for this repo can drop all black config here.
1: https://black.readthedocs.io/en/stable/usage_and_configuration/file_collection_and_discovery.html#gitignore
Refs: opensafely-core/repo-template#85
> Remove unnecessary black config

- jobrunner/cli/local_run.py
- tests/cli/test_local_run.py
Sadly, this feature lacked a functional test, and one function in the
chain did not pass on the user supplied values.
This change adds a fully docker functional test, and checks the user
supplied cpu/memory values were applied to the docker container.
> Fix: actually apply the cpu/memory limits for local run

- jobrunner/config.py
- jobrunner/executors/local.py
- jobrunner/job_executor.py
- jobrunner/lib/docker.py
- jobrunner/run.py
- tests/test_local_executor.py
- tests/test_run.py
Fixes #453
This adds a tuneable config for how many retries we allow before
failure.
> fix: retry on docker inpsect timeouts

- jobrunner/create_or_update_jobs.py
- jobrunner/run.py
- jobrunner/tracing.py
- tests/cli/test_prepare_for_reboot.py
- tests/test_run.py
- tests/test_tracing.py
Now that we have "tick" traces, we don't really need these anymore, and
the add noise that needs filtering out in Honeycomb
> chore: remove the ENTER states from the job trace

- jobrunner/cli/local_run.py
This allows us to re-use it wholesale in opensafely-cli.
> chore: factor out the  stata licene error message

- jobrunner/executors/local.py
- jobrunner/run.py
- tests/test_local_executor.py
- tests/test_run.py
Instead, record that it happened, but don't fail the job. The idea is
that we can then be alerted to it happening, but when it's over, the job
continues.
Also, increase get_status timeout from 10s to 15s, we a) occasionally we
saw it in GHA CI, and b) having it slow down a bit when docker is
blocking is no bad thing
Fixes #546
> fix: don't error the job on ExecutorRetry

- jobrunner/executors/local.py
- jobrunner/executors/volumes.py
- jobrunner/job_executor.py
- jobrunner/lib/__init__.py
- jobrunner/lib/docker.py
- tests/lib/test_init.py
- tests/test_local_executor.py
Using seconds meant that the  truncation to nearest second made it
possible for telemetry timestamps to move backwards in time which causes
all kinds of complexity.
This changes the semantics of JobStatus.timestamp to be integer
nanoseconds, which should mean it never goes backwards. To support this
for the PREPARED state, we write the ns timestamp into as the contents
of the .opensafely-timestamp, so we can read them out later.
Note, this doesn't change the find new files logic, which still uses the
filesystem mtime metadata for finding new files.
Also, the parsing of timestamps from docker was just completely busted,
so this fixed that and added more tests.
> fix: change JobStatus.timestamp to ns precision

- jobrunner/tracing.py
- tests/test_tracing.py
This just means giving it an explicit empty context.
> fix: stop job traces picking up loop trace as parent

- jobrunner/executors/volumes.py
You can't open a file that's already open on Windows.
So, don't do that.
> fix: workaround windows filesystem, again

- jobrunner/executors/volumes.py
- tests/test_local_executor.py
Check for volume directory existance first, which is a common case, to
avoid spaming exceptions in logs
> chore: reduce log spam in BindMountVolumeAPI

- jobrunner/cli/local_run.py
- jobrunner/create_or_update_jobs.py
- tests/test_create_or_update_jobs.py
I'm not sure if this has always been broken, or whether things have changed elsewhere in the codebase such that assumptions about the contents of `current_jobs` no longer hold.
In any case, the bug would be triggered when all the actions a user requested were already running *and* some other action which they didn't request had already failed.
As the cost of passing in `job_request` we can radically simplify the logic here.
> fix: Fix buggy `assert_new_jobs_created` logic

- jobrunner/executors/volumes.py
- tests/test_local_executor.py
Currently, the bindmount api's delete_volume method errors on TPP once
it errors on one file. This needs fixing, but may take a bit of time.
To handle it better in the meantime, record but don't error on these
files, and log them. That way, we delete all the files we can, and leave
only those we can't.
> fix: delete as many files as we can

- jobrunner/executors/volumes.py
- tests/test_local_executor.py
Also, ensure that this code can never cause the job to fail, by
expanding the try/except body.
> Ensure rmtree onerror handler records Paths not strings

- jobrunner/cli/local_run.py
- jobrunner/config.py
- jobrunner/executors/local.py
- jobrunner/executors/volumes.py
- tests/test_local_executor.py
Current, delete_volume() doesn't work properly with the
BindMountVolumeAPI. Because the containers are run as root, files they
create are owned by root, and this prevents jobrunner from deleting
them, and we currently manually have to delete them.
This change runs jobs with the jobrunner uid/gid when using
BindMountVolumeAPI, which solves the problem.
I have tested that all our current images work when run as non-root with
some sample studies, so I think this is good to go.
> fix: run as non-root user with BindMountVolumeAPI

- jobrunner/executors/local.py
Otherwise, HOME=/, and any code which tries to write to $HOME will fail
when not running as root.
We do set HOME=/tmp in `opensafely exec` for this reason too.
> fix: set HOME=/tmp for executing with BindMount volume api

- jobrunner/cli/kill_job.py
- jobrunner/executors/local.py
- jobrunner/executors/logging.py
- jobrunner/job_executor.py
- jobrunner/run.py
- tests/factories.py
- tests/fakes.py
- tests/test_local_executor.py
- tests/test_logging_executor.py
- tests/test_run.py
* some files use `job` to mean an instance of `JobDefinition`, others use `job` to mean `Job` and `definition` to mean `JobDefinition`
* in isolation this is fine (and makes lines shorter), but when working on issues that cut across the entire repo it adds unnecessary cognitive load
* comment the one ambiguous call for future work (could receive a `JobDefinition` or `Job`)
> chore: rename variables to be more consistent

- jobrunner/cli/local_run.py
- tests/conftest.py
* the docker clean-up process was leaving volumes & running containers behind with each run - tidy them up!
* but don't clean up any debug containers/volumes that were produced by other means
> chore: cleanup left-over containers from pytest runs

- tests/test_local_executor.py
* this was leaving a running vol & container behind
> fix: add a missing cleanup to a local executor test

- .github/workflows/tests.yml
* even when running `just test-no-docker` some tests failed because they expected the presence of a docker executable
* use brew to install docker/[colima](https://github.com/abiosoft/colima) which allows these tests to pass
* use macos-12, because when I tried macos-13 I waited 40mins for a GHA runner to become available 😱
> feat: run tests on MacOS 12

- jobrunner/cli/kill_job.py
- jobrunner/cli/prepare_for_reboot.py
- jobrunner/executors/local.py
- tests/conftest.py
- tests/test_integration.py
- tests/test_local_executor.py
The integration tests currently only run using one of the APIs that we support. We should run the tests on both APIs, which will hopefully catch more bugs more quickly.
> chore: integration test for bindmountapi

- jobrunner/config.py
- jobrunner/extractors.py
- jobrunner/lib/commands.py
- scripts/update-docker-image.sh
- tests/test_extractors.py
ehrql now tags its images with both `databuilder` and `ehrql`: https://github.com/opensafely-core/ehrql/pull/1214
This means that users can use `ehrql:v0` in their project.yaml and in `opensafely exec` in place of databuilder, before we've completed the full renaming.
(Also requires an opensafely-cli PR after this one is merged)
> feat: Add ehrql to allowed images

- jobrunner/config.py
- jobrunner/executors/local.py
For the mechanism which creates and configures this network see:
* https://github.com/opensafely-core/backend-server/pull/105
> Use custom network to restrict network access for db jobs

- scripts/archive.sh
* some simple fixes that must have somehow got lost when this script was created & first used
* it's possible that there are some old archive files that contain gzipped data but have the xz extension - I guess we'll find out if/when we need them. If we encounter a "corrupt" xz file, we should try to remember to experiment with changing the extension to gz...!
> fix: correct bugs in archive script

- scripts/mount-job-volume.sh
* this was found on the production service
> fix: use correct docker label for mount-job-volume

- docs/local_executor_run.md
- jobrunner/config.py
- jobrunner/executors/local.py
- jobrunner/job_executor.py
- jobrunner/run.py
- tests/factories.py
- tests/test_local_executor.py
- tests/test_run.py
* make lots of executor states more consistent, in two ways:
* between different but related pathways (e.g. killed & cancelled jobs)
* between statuses returned from action methods (e.g. `finalize()` and statuses returned from `get_status()`
* enable finalize to run in a "logs_only" mode for jobs that have been cancelled
> feat: preserve logs of user cancelled jobs

- jobrunner/cli/local_run.py
- jobrunner/config.py
- jobrunner/run.py
- tests/test_integration.py
Instead of randomising we now order jobs by how many jobs are already running in that jobs workspace, and then by age.
There are many things other than workspace we could partition on (e.g. user, project, organisation) but workspace is directly available on the job object, is easy to explain, and doesn't have the effect of penalising users who have to work on several different things.
Note that this doesn't prevent a large job request from grabbing all available slots if nothing else is running when it is submitted. But it does mean that the next slot that becomes free will go to a job from a different workspace.
Because the number of running jobs will change as we work our way through the set of active jobs we have to update the counts and re-sort the jobs on each iteration. This is not …
> Use (hopefully) fairer job processing order

- tests/factories.py
- tests/test_run.py
* we have at least three classes in the mix - ExecutorState, State & JobStatus - here we have a dictionary of JobStatus objects which is called `state`, `job_statuses` is better
* this only affects our test classes
> chore: rename state to status to match contents

- scripts/update-docker-image.sh
And prevent attempts to update `databuilder` directly. Previously updating `databuilder` would update the `ehrql` version, but not vice versa so it was possible for them to get out of sync.
> Use `ehrql` rather than `databuilder` as canonical image name

- .github/workflows/tests.yml
This uses [alls-green](https://github.com/re-actors/alls-green) to set up a job that depends on previous jobs, capturing our matrixed jobs too, so we can configure one required check in the repo settings.
> Configure required checks

- jobrunner/record_stats.py
- pyproject.toml
- tests/test_record_stats.py
We're sometimes seeing missing metrics for some jobs. This addes a lot
more data to the tick traces so we can try diagnose why we have missing
metrics.
Part of #634
> Add telemetry to the stats collection

- jobrunner/lib/docker_stats.py
- tests/lib/test_docker_stats.py
We use `str.lstrip("os-job-")` to filter the list of metrics. However,
strip doesnt work like that, a fact that has bitten me many times
previously.
It meant that if a job id started with any of the 'osjb' characters, it
would be stripped from the id in the dict, leadint to it not being
found.
Sadly, we're on 3.8, so we can't use removeprefix, so we fake it.
This was found by the added telemetry in earlier PR, but also needed
some cowboyed additonal bits in prod, to confirm, now undone.
> Fix missing job metrics

- jobrunner/run.py
This adds a natural priority to db jobs, ensuring they will always be
considered before cpu jobs.
Currently, enough cpu jobs to hit MAX_WORKERS will block db jobs from
starting, as they will be considered first.
Note, this is still sorted *after* workspace, so the fairness is still
preserved.
There are not tests for this, as this code currently has no test
coverage, as its a bit fiddly to implement.
Pulling in the bug fix from other branch, as its affect tests here, but am waiting on review for that branch
> Sort jobs by if they need db or not

- dotenv-sample
- jobrunner/config.py
- tests/test_service.py
This is preparatory as the new ones are not yet in use. We also change the configuration behaviour so that database names are now only added to the config if a value for them exists in the environment. This means that job-runner instances will refuse to accept job requests for databases they have not been configured to run, rather than accepting the job and then throwing an error later.
> Remove old database names and add new ones

- jobrunner/config.py
- tests/test_config.py
And add test which actually exercises this code.
> Fix missing f-string

- jobrunner/create_or_update_jobs.py
* better align with what users expect the system to do
* previously users were forcing run all jobs (generating excessive load) or tediously manually running failed jobs
* fixes https://github.com/opensafely-core/job-runner/issues/651
> fix: re-run failed jobs by default when required

- .github/workflows/tests.yml
This reverts commit 251d21497f2b6ce96d8a87e341643cc2740a8212.
Fixes https://github.com/opensafely-core/job-runner/issues/660
> Revert "Apply the QEMU workaround for colima"

- jobrunner/cli/local_run.py
- jobrunner/models.py
* this is redundant as of https://github.com/opensafely-core/job-runner/pull/657
> chore: remove unused force_run_failed

- jobrunner/config.py
- jobrunner/executors/local.py
- jobrunner/executors/volumes.py
- jobrunner/job_executor.py
- jobrunner/lib/docker.py
- jobrunner/run.py
- tests/test_local_executor.py
- tests/test_run.py
- Use correct privacy strings in tests
- Limit level 4 file size
> level 4 limits

- jobrunner/cli/local_run.py
- jobrunner/executors/local.py
- jobrunner/executors/volumes.py
- jobrunner/lib/database.py
- jobrunner/lib/log_utils.py
- jobrunner/models.py
- jobrunner/run.py
- tests/cli/test_kill_job.py
- tests/cli/test_local_run.py
- tests/cli/test_prepare_for_reboot.py
- tests/conftest.py
- tests/factories.py
- tests/lib/test_database.py
- tests/test_local_executor.py
- tests/test_run.py
This PR fixes local_run command to run and surface the new level 4 file checks we added
- update black formatting
- improve excluded outputs log formatting
- Perform level 4 files checks in local_run
- Add level4_excluded_files results filed to Job db
Fixes #675
> local l4 checks

- jobrunner/cli/add_job.py
- jobrunner/create_or_update_jobs.py
- pyproject.toml
- tests/cli/test_add_job.py
This was not previously covered in tests, and it broke with the codelist
checking changes.  It's used in the backed-server test suite, which is
how I noticed.
If fixed, and added test coverage, which allowed me to bump the coverge
minimum a bit.
> Fix add_job cli command

- jobrunner/create_or_update_jobs.py
We set this for failed and successful jobs, but not for cancelled actions, despite them being treated as failed jobs.  This fixes that.
Ref: opensafely-core/job-server#3770
> Set Job.completed_at when cancelling

- scripts/update-docker-image.sh
Pulling `ehrql:v1` should not attempt to pull `databuilder:v1` because there is no such image.
> Remove automated pull of `databuilder` alias

- jobrunner/config.py
- jobrunner/executors/local.py
- jobrunner/job_executor.py
- jobrunner/models.py
- jobrunner/record_stats.py
- jobrunner/sync.py
- tests/conftest.py
- tests/factories.py
- tests/test_local_executor.py
- tests/test_record_stats.py
- tests/test_sync.py
- Collect and store per-job aggregate metrics
- Expose metrics from executor.
- Expose metrics in sync protocol
> aggregate job metrics

- jobrunner/config.py
- jobrunner/executors/local.py
- jobrunner/job_executor.py
- jobrunner/models.py
- jobrunner/record_stats.py
- jobrunner/sync.py
- tests/conftest.py
- tests/factories.py
- tests/test_local_executor.py
- tests/test_record_stats.py
- tests/test_sync.py
Reverts opensafely-core/job-runner#686
> Revert "aggregate job metrics"

- jobrunner/config.py
Makes allowed file types consistent with those listed [in the output review docs](https://docs.opensafely.org/releasing-files/#allowed-file-types)
> drop pdf from L4 file types

- jobrunner/config.py
- jobrunner/executors/local.py
- jobrunner/job_executor.py
- jobrunner/models.py
- jobrunner/record_stats.py
- jobrunner/sync.py
- tests/conftest.py
- tests/factories.py
- tests/lib/test_database.py
- tests/test_local_executor.py
- tests/test_record_stats.py
- tests/test_sync.py
This PR contains the 3 reverted commits https://github.com/opensafely-core/job-runner/pull/686, and then an additional commit to fix the use of a global variable to cache the connection string in multithreaded application.  This is known to be Bad Juju, and I regret the error.
The sync, run and stats thread *all* have a db connection to the metrics
db, so this cause sqlite to barf.
This was not caught in the test suite because we do not currently have
a functional test that runs the full multithreaded service and tries to
run a job with it.  This is in theory possible (it's what the
a backend-server tests for the test backend do), but its also hard to
set up and slow and requires lxc currently, so I have not done that
here.
Once this lands, I will test it does fix the multithreaded issue …
> Collect, store and send aggregate metrics, take 2

- jobrunner/lib/docker_stats.py
- jobrunner/record_stats.py
- tests/test_local_executor.py
- tests/test_record_stats.py
This involves tracking the container ID associated with each job and resetting the metrics if we spot that the ID has changed.
Closes #706
> Reset cumulative metrics after job restart

- jobrunner/config.py
In agreement with output checkers,  we are removing support for tsv
files as valid level 4 files
> Remove .tsv support for Level 4 files

- jobrunner/tracing.py
- tests/test_tracing.py
We want to have jobrunner and airlock both emitting telemetry from a backend, but they share the same env var config.
The motivation for this change was to encode a default OTEL_SERVICE_NAME in the job-runner so we don't end up mixing their data in Honeycomb
Along the way, I fixed a couple of otel related issues
- use a top level Resource to provide some of the static metadata, including tagging with backend name
- fixed a visualisation issue in honeycomb that shows a missing root span (it was annoying me).
> Update otel config

- jobrunner/tracing.py
- tests/conftest.py
- tests/test_tracing.py
This resulted in some fix to the configuration too,
as consuming OTEL_SERVICE_NAME was not being done correctly
It does involve some messy reaching into otel internals though
> Test the setup_default_tracing()

- jobrunner/tracing.py
- tests/test_tracing.py
Workaround for a bug in docker-compose
> Strip quotes from OTEL_EXPORTER_OTLP_HEADERS value

- jobrunner/cli/manifests.py
- jobrunner/executors/local.py
- pyproject.toml
- **Backport fixes from production backfill**
- **Reorder the level 4 checks to optimise finalize time.**
> avoid expensive csv checks

- jobrunner/tracing.py
- tests/test_tracing.py
This will allow us to calculate for each tick how long a job has been in
a certain state, and drive alerts from that
> Capture status_code_update_at timestamp.

- .github/workflows/tests.yml
Whilst we are still not running job-server inside docker, we need
job-runner to work under the system python. Currently, TPP is on
20.04/pyh38, andw e want to upgrade to 22.04/py3.10
job-runner does work on 3.10, as its bundled in opensafely-cli, and
that's been running on 3.10 fine for anyone on 22.04 for ages.
But this formalises it in CI.
> Test under python 3.10

- .github/workflows/build_and_publish.yaml
- .github/workflows/tests.yml
- tests/cli/test_kill_job.py
- tests/cli/test_prepare_for_reboot.py
- tests/test_local_executor.py
This was prompted by a bug in setup-python@v5, which means that the
post-clean-up job will fail if you do not actually install anything in
pip, as the cache directory will not be created. This has hit a few of
our GHA workflows.
https://github.com/actions/setup-python/issues/815
The reason this was triggering for job-runner was that the current CI
setup was pretty much broken.
Firstly, the PYTHON_VERSION env var was not being set, which meant that
every test run was always testing 3.8, not 3.9 or 3.10 as per the
matrix.  Fixing this meant a bit of windows/powershell finesse.  It
always explains the fact that for some reason, even though we have 22.04
in the matrix, we did not run the tests on it (this was what triggered
the above failure).
Additionally, we were going to the trouble of …
> Fix CI again

- jobrunner/cli/local_run.py
We allow the user to set the number of concurrent jobs using the `--concurrency` argument and use this to update the worker limit, but we didn't update the database worker limit.
The distinction is meaningless for local jobs in any case because these jobs are just generating dummy data, but it meant that jobs ran with less parallelism than expected. It also lead to "Waiting on available database workers" messages appearing in the log output which caused confusion and anxiety.
> Set MAX_DB_WORKER limit in `local_run`

- docker/.gitignore
- docker/Dockerfile
- docker/dependencies.txt
- docker/docker-compose.yaml
- docker/justfile
- docker/ssh/config
- jobrunner/executors/local.py
- jobrunner/executors/volumes.py
- jobrunner/lib/docker.py
The job-runner docker image is in a half working state. A couple of attempts have previously been made to figure out how to get it to be able to use the host's docker and file system to run jobs, but they were messy and also didn't fully work.
However, in docker 4.26.0, released Dec '23, they added support for [`--group-add`](https://docs.docker.com/desktop/release-notes/#4260), which made the permissions much simpler.  
Now we are on 22.04, we have a more up to date docker, and docker-compose v2, so this is simpler change. Using this new features, this change cleans up some of the old approaches.
We use a simple trick to make bind mounts work - the bind mounts must use the same path inside the container as on the host.  This avoids us needing to add new configuration options and logic, …
> Fix docker image to actually work

- jobrunner/cli/kill_job.py
- tests/cli/test_kill_job.py
> Full job id matching

- jobrunner/lib/database.py
Ensure that sqlite3 always uses URIs for db connections.
Different versions of sqlite3 may or may not set the [USE_URI compile time option](https://www.sqlite.org/compile.html#:~:text=SQLITE_USE_URI), so make sure it's always used, irrespective.
> Use uri=True for db connections

- jobrunner/actions.py
- pyproject.toml
- requirements.prod.txt
- tests/test_actions.py
- Bump the pipeline version to 2024.09.27.131013
- Associated changes to code: Remove use of the `exclude_unset` keyword argument which is related to Pydantic
- Associated changes to tests: Use `Pipeline.build()` and ensure `dummy_data_file` is `str` type
> Bump to pipeline 2024.09.27.131013

- pyproject.toml
- requirements.prod.txt
Make version 4 of pipeline available for choosing. 
It ceases supporting cohort extractor actions and does not use an `expectations` section in the `project.yaml` file.
> Bump to pipeline 2024.10.08.124104

- jobrunner/service.py
- tests/test_service.py
Currently, manually enabling database maintenance mode is awkward, as by
default it will just get switch off again by the regular automatic
check. So you have to remember to stop that first, which is awkward,
then restart it, for more awkwardness
Instead, this change adds an explicit flag check for
`manual-db-maintenance` - if that is set, we skip the automated check
altogether.
This will be added to the jobrunner justfile in backend-server as
a documented command in a separate PR.
> Add a dedicated manual maintenance mode flag

- pyproject.toml
- requirements.prod.txt
- Part of https://github.com/opensafely-core/pipeline/issues/344
- More informative error message when parsing `project.yaml` files with empty actions
- Contains code to allow optional use of fast YAML parser, needs separate PR to install requirements
> fix: Bump pipeline version

- docker/Dockerfile
Using docker volumes does not seem to work reliably, and production use
is all bind mount anyway
> Default to BindMountVolumeAPI in docker image

- .github/workflows/build_and_publish.yaml
The tagging is really for changes relevant to opensfely-cli/local_run to
consume. For the docker image, we want any change, e.g. updated
dependencies.
> Build and publish docker on every commit.

- jobrunner/job_executor.py
- jobrunner/lib/database.py
- pyproject.toml
- tests/lib/test_database.py
- tests/lib/test_string_utils.py
- tests/test_sync.py
* write a few simple tests to cover more of the codebase
* ignore some uninteresting parts of the codebase
* increase the target to 84
> Increase test coverage requirement to 84%

- jobrunner/service.py
- tests/test_service.py
It incorrectly assumed the flag was being set by the caller, and
returned early. The return value is meant to be informative, rather than
acted upon. The tests only tested the return value.
Fixed the function to DTRT, and the tests to check the flag value as
well as the return value
Fixes #762
> Fix manual maintenance mode

- jobrunner/cli/add_job.py
- jobrunner/lib/github_validators.py
- tests/conftest.py
- tests/lib/test_github_validators.py
The previous approach of forbidding slash characters had the effect of also rejecting legitimate branch names (see issue below). A better approach, as suggested by Mike Kelly, is to check the commit against `refs/heads/{branch-name}` which naturally rejects anything which isn't a genuine branch.
Closes https://github.com/opensafely-core/job-server/issues/4998
> Better targeted Github branch validation

- jobrunner/executors/local.py
- tests/cli/test_kill_job.py
- tests/conftest.py
- tests/test_local_executor.py
This is a prerequisite for doing the agent-controller split.
> Save job results to disk and not in memory

- DEVELOPERS.md
- dotenv-sample
- jobrunner/tracing.py
- justfile
- local-setup.sh
- tests/test_tracing.py
Fixes #809 
Update developer docs to document how to run jobs in the test backend, and fix some out of date docs at the same time.
Also adds a small script to update the storage dirs based on your local paths
And a drive-by fix for a error that was being thrown when trying to log a NonRecordingSpan
Note that the docs on running jobs on the test backend depend on this [backend-server PR](https://github.com/opensafely-core/backend-server/pull/270)
> Update developer docs and document how to run jobs on the test backend

- jobrunner/agent/task_api.py
- jobrunner/controller/task_api.py
- jobrunner/models.py
- jobrunner/schema.py
- tests/agent/test_task_api.py
- tests/controller/test_task_api.py
- tests/factories.py
- no timestamps - agents gonna do its own telemetry, at least for now
- add backend field, as controller needs to support multiple
- get rid of TaskStage - the controller doesn't care, just use a string
- renamed completed_at to finished_at, as semantically different
from completed flag
> Task API tweaks

- pyproject.toml
The `pytest --cov` invocation is a convenient way of checking how well a given set of tests covers a given set of files and is key to a fast feedback loop when addressing coverage issues. See:
https://github.com/opensafely-core/ehrql/wiki/Tips-for-using-pytest#coverage
However, currently it fails with the error:
pytest_cov.CentralCovContextWarning: Detected
dynamic_context=test_function in coverage configuration. This is
unnecessary as this plugin provides the more complete --cov-context
option.
However we don't want to remove this setting because it's required for the `coverage run` invocation which we use in CI and we want to maintain that because it gives a nicer story for combining coverage from multiple runs. So instead we just ignore the warning.
Related Slack thread: …
> Ignore warning when running `pytest --cov`

- jobrunner/agent/main.py
- jobrunner/agent/tracing.py
- jobrunner/tracing.py
- tests/agent/test_agent.py
- tests/agent/test_tracing.py
Add tracing for the agent loop.
Sets common attributes from the task (which later may not be job-related), and then attributes from the job. I didn't add all job attributes, and this is a job definition rather than a job, so it doesn't have quite the same things as the main jobrunner.tracing module has for a job.  We may need to revisit what's actually useful to include.
On each update_controller call, we also add the final job status and results/error attributes if there are any.
> add telemetry for the agent loop and runjob tasks

- jobrunner/models.py
For hysterical raisins, we don't autocreate all tables. Adding an
explicit migration ensures that we will.
We expect to move this all to djagno ORM soonish anyway.
Testing migrations is hard. This was manually tested against the curret
test-backend db.
```
$ cp test-backend.db.sqlite workdir/db.sqlite
$ sqlite3 workdir/db.sqlite 'SELECT * FROM tasks'
Error: in prepare, no such table: tasks (1)
$ python3 -m jobrunner.cli.migrate
2025-04-11 10:36:43.520Z Skipping migration 1 as already applied
2025-04-11 10:36:43.521Z Skipping migration 2 as already applied
2025-04-11 10:36:43.521Z Skipping migration 3 as already applied
2025-04-11 10:36:43.522Z Applied migration 4:
CREATE TABLE tasks (
id TEXT,
backend TEXT,
type TEXT,
definition TEXT,
active BOOLEAN,
created_at int,
finished_at int, …
```
> Ensure tasks table is created

- DEVELOPERS.md
Use the test-age-distribution repo as an example instead of os-demo-research which is old enough to still be using cohort-extractor code, and references images by latest. It doesn't work with add-job and switching to a different test repo that does work seems like a better option than fixing it.
> Update the add-job docs with a repo that works

- jobrunner/agent/main.py
- jobrunner/controller/main.py
- jobrunner/executors/local.py
- jobrunner/job_executor.py
- tests/agent/stubs.py
- tests/agent/test_agent.py
- tests/agent/test_tracing.py
- tests/factories.py
Implements cancelling jobs in the agent. Note that the controller only includes job id in the CANCELJOB task definition, which means that if we need to write job logs, there will be some information that we don't have. We could always have the controller send this too, but I haven't done that yet and have left a TODO.
Testing locally is a bit tricky, this is what I did:
1) Edit `main()` in `agent/main.py` so that the agent only runs one loop at a time:
```
def main(exit_callback=lambda _: True):
...
```
2) Add a job with `just add-job`
```
just add-job https://github.com/opensafely/test-age-distribution generate_dataset -f
```
Make a note of the job id
3)  `just run-controller`
You should see the job get picked up and log that it's executing. Leave it running for the rest of the steps.
4) …
> Implement agent handle_cancel_job_task

- tests/fixtures/full_project/analysis/dataset_definition.py
- tests/fixtures/full_project/project.yaml
- tests/fixtures/full_project/test-data/ehrql-dummy-data.csv
- tests/test_integration.py
Add an integration test to exercise agent/controller together
This uses the same setup and actions as the existing cohortextractor and ehrql integration tests. Also parametrizes the test and makes some minor updates to the fixture data so we can run the whole thing on both ehrql and cohortextractor.
> Make an agent/controller version of the ehrql integration test

- jobrunner/agent/main.py
- jobrunner/controller/main.py
- jobrunner/executors/local.py
- jobrunner/executors/logging.py
- jobrunner/job_executor.py
- jobrunner/run.py
- tests/agent/stubs.py
- tests/agent/test_agent.py
- tests/factories.py
- tests/test_local_executor.py
Fixes #860 
- removes the cancelled flag from JobDefinition
- adds a cancelled arg to the executor api `get_status()` and `finalize()`, True when these methods are called from a canceljob task in the agent
-  persists the cancelled status in the job metadata so that subsequent calls to get_status can know if a job was already cancelled
- this means that we now call finalize() on all cancelled jobs, even if they haven't started, so that we can persist the metadata, including the created_at/cancelled status.
> Remove cancelled flag on JobDefinition

- jobrunner/tracing.py
- tests/test_tracing.py
We log an error if we try to set span metadata with a type that otel can't handle. None is one of those values, but it's not very interesting, and because it happens quite a lot, we end up with logs full of these errors. Now we just coerce it to a string without logging it.
> Handle None values in span attributes without logging

- jobrunner/agent/main.py
- jobrunner/agent/tracing.py
- jobrunner/cli/kill_job.py
- jobrunner/cli/retry_job.py
- jobrunner/controller/main.py
- jobrunner/lib/log_utils.py
- jobrunner/record_stats.py
- jobrunner/run.py
- jobrunner/sync.py
- jobrunner/tracing.py
- tests/agent/stubs.py
- tests/agent/test_agent.py
- tests/agent/test_tracing.py
- tests/lib/test_log_utils.py
Fixes #856 
- Gets dev coverage to 100% 
- Updates the results attributes that we trace when a job completes to replicate what we currently send in prod
> Tracing and tests

- jobrunner/agent/main.py
- jobrunner/agent/tracing.py
- jobrunner/controller/main.py
- jobrunner/executors/local.py
- jobrunner/job_executor.py
- jobrunner/lib/docker.py
- tests/agent/stubs.py
- tests/agent/test_agent.py
- tests/cli/test_kill_job.py
- tests/controller/test_main.py
- tests/test_local_executor.py
Fixes: #861
The original plan has been to persist the error information in a separate error.json file. However, this proved to be awkward, as it required plumbing a bunch of extra error related methods that mirrored the metadata methods, e.g. read/write_job_error, get_error, etc.
Instead, we chose to embed the error information in the already persisted metadata.json that is written by ``finalize_job`
This involved making finalize_job work on a job in any state, as an error can happen at any times, and storing as much info as it has available.
Along the way, we refactored away the get_results/get_metadata executor API calls, and instead just return the metadata as part of every get_status() call. This simplified a bunch of things, as we already were loading and checking for metadata.json …
> Get errors to persist to disk and update controller with results 

- jobrunner/cli/add_backend_to_job.py
- jobrunner/cli/add_job.py
- jobrunner/controller/main.py
- jobrunner/create_or_update_jobs.py
- jobrunner/lib/database.py
- jobrunner/models.py
- jobrunner/sync.py
- justfile
- tests/cli/test_add_backend_to_job.py
- tests/lib/test_database.py
- tests/test_create_or_update_jobs.py
- tests/test_integration.py
- tests/test_sync.py
Fixes #879 
- adds a backend attribute to Job
- and to JobRequest (not a db object, but it's convenient to include it as a representation of the job-server job request)
- job-server already includes the backend in the job request response, so we can use it now when creating jobs in `sync`
- Use the new job.backend to set the task's backend in the controller loop
- Add a cli command to add the backend to existing jobs based on their SavedJobRequest, or if not available, the config.BACKEND; this is intended to run once only per backend before we move the controller and the jobs DB out of the backends and merge them
Note this deliberately doesn't do any filtering of jobs by backend yet (for determining dependencies etc). It doesn't need it while the db is still backend-specific and it will …
> Add backend to job model

- .github/workflows/tests.yml
- docker/justfile
- dotenv-sample
- jobrunner/actions.py
- jobrunner/agent/main.py
- jobrunner/cli/add_job.py
- jobrunner/config/agent.py
- jobrunner/config/common.py
- jobrunner/config/controller.py
- jobrunner/controller/main.py
- jobrunner/create_or_update_jobs.py
- jobrunner/executors/local.py
- justfile
- tests/agent/test_main.py
- tests/cli/test_add_job.py
- tests/controller/test_main.py
- tests/test_actions.py
- tests/test_config.py
- tests/test_create_or_update_jobs.py
- tests/test_integration.py
- tests/test_sync.py
- Make `USING_DUMMY_DATA_BACKEND` agent-only config
The controller will soon become responsible for all backends so logic about whether the current backend is a dummy data one belongs with the agent only. Also removed references to the no-longer-active "expectation" backend
- Moves database URL validation to the agent and just validates database name is one of the allowed ones ("default" or "allow_t1oo") in the controller
- Removes code that just handled modifiying dummy data args for cohort-extractor actions
> Move dummy data backend config to agent only

- jobrunner/agent/main.py
- jobrunner/executors/local.py
- tests/test_local_executor.py
This re-adds the two commits from #894 that were lost by force-pushing to dev.  (See [activity log](https://github.com/opensafely-core/job-runner/activity?ref=dev).)
>  Avoid handling exceptions in the executor and raise instead

- jobrunner/agent/main.py
- jobrunner/controller/main.py
- jobrunner/lib/database.py
- tests/agent/test_agent.py
- tests/controller/test_main.py
- tests/lib/test_database.py
For now the only errors we treat as transient are "database locked" errors but we may expand this in future.
Closes #908
> Don't fail jobs on transient errors

- jobrunner/agent/main.py
- jobrunner/agent/task_api.py
- jobrunner/config/agent.py
- jobrunner/config/controller.py
- jobrunner/controller/main.py
- jobrunner/create_or_update_jobs.py
- jobrunner/lib/docker.py
- jobrunner/lib/git.py
- jobrunner/queries.py
- jobrunner/tracing.py
- tests/agent/test_task_api.py
- tests/controller/test_main.py
- tests/factories.py
- tests/lib/test_git.py
- tests/test_create_or_update_jobs.py
- tests/test_integration.py
- tests/test_workspace_state.py
Fixes #882 
This updates all the main agent/controller code to filter jobs/tasks by backend where necessary.
It does not yet address:
- flags
- cli commands
- config that needs to be per-backend
- fetching job requests from job server for all backends
> Filter jobs/tasks by backend

- jobrunner/agent/task_api.py
- jobrunner/create_or_update_jobs.py
We only need transactions around multiple statements. sqlite's default
autocommit behaviour DTRT with respecting busy_wait timeout with single
statment write statements.
So the changes reverted here didn't really do anything, and could cause
confusion.
> Remove quickfix transactions added from incident

- jobrunner/cli/kill_job.py
- jobrunner/cli/retry_job.py
- jobrunner/controller/main.py
- jobrunner/lib/database.py
- tests/controller/test_main.py
- tests/lib/test_database.py
SQLite's LIKE queries are case-insensitive [by default](https://www.sqlite.org/lang_expr.html#the_like_glob_regexp_match_and_extract_operators). This means that left-anchored prefix queries such as:
```
my_col LIKE 'some_prefix_%'
```
which you might expect to make use of an index on `my_col` will in fact always use a sequential scan.
SQLite also provides the GLOB operator which is very similar to LIKE but uses `*` and `?` instead of `%` and `_` and, more importantly, is case sensitive by default.
It is possible to change LIKE to be case sensitive using a pragma, but the docs very strongly [discourage this](https://www.sqlite.org/pragma.html#pragma_case_sensitive_like):
> This pragma is deprecated and exists for backwards compatibility only. New applications should avoid using this …
> Use GLOB rather than LIKE for partial ID matches

- jobrunner/agent/tracing.py
When switching from old metadata.json to new, it might not be there
> Handle missing cancelled field

- dotenv-sample
- jobrunner/config/agent.py
- jobrunner/config/common.py
- jobrunner/config/controller.py
- jobrunner/controller/main.py
- jobrunner/create_or_update_jobs.py
- jobrunner/executors/local.py
- tests/agent/test_task_api.py
- tests/cli/test_add_backend_to_job.py
- tests/controller/test_main.py
- tests/factories.py
- tests/test_config.py
- tests/test_create_or_update_jobs.py
- tests/test_integration.py
- tests/test_job_resource_weights.py
- tests/test_local_executor.py
Fixes #904
- Adds a BACKENDS config variable to define known backends, and validates job requests against it.
- Updates controller config that will need to be backend-specific 
- MAX_WORKERS
- MAX_DB_WORKERS
- DEFAULT_JOB_CPU_COUNT
- DEFAULT_JOB_MEMORY_LIMIT
- JOB_RESOURCE_WEIGHTS (now read from backend-specific ini files)
- LEVEL4_FILE_TYPES remains constant across backends, but is now passed explicitly in the task definition
MAX_WORKERS is the only env variable which is currently defined in backends, and will need to change to include the backend name (i.e. MAX_WORKERS becomes TEST_MAX_WORKERS and TPP_MAX_WORKERS).
> Update config for multiple backends

- jobrunner/cli/add_backend_to_flags.py
- jobrunner/cli/flags.py
- jobrunner/controller/main.py
- jobrunner/models.py
- jobrunner/queries.py
- jobrunner/service.py
- jobrunner/sync.py
- tests/cli/test_add_backend_to_flags.py
- tests/cli/test_flags.py
- tests/controller/test_main.py
- tests/test_queries.py
- tests/test_service.py
- tests/test_sync.py
Fixes #922
Update the flags table and queries to always filter by a backend.
Punts on how the db-maintenance flag will be set for now and just uses the agent's BACKEND setting.
Also adds a cli command to add the current backend to any existing flags, intended to be run while the controller is still inside the backend and removed later (along with the add_backend_to_job command)
> Per-backend flags

- dotenv-sample
- jobrunner/cli/add_backend_to_flags.py
- jobrunner/cli/flags.py
- jobrunner/config/agent.py
- jobrunner/config/controller.py
- jobrunner/controller/main.py
- jobrunner/models.py
- jobrunner/queries.py
- jobrunner/service.py
- jobrunner/sync.py
- tests/cli/test_add_backend_to_flags.py
- tests/cli/test_flags.py
- tests/conftest.py
- tests/controller/test_main.py
- tests/test_integration.py
- tests/test_queries.py
- tests/test_service.py
- tests/test_sync.py
Fixes #905 - remove the unused backend parameter from jobserver api calls
Fixes #915 
Loop through the known BACKENDS in `sync()` and sync each one in turn.
This means that the controller will need to know about the JOB_SERVER_TOKEN for each backend, so there are new expected environment variables that populate this config (<BACKEND>_JOB_SERVER_TOKEN for each backend). While the controller is still running inside the backends, the `BACKENDS` variable can be set to a single backend (e.g. `test`) and will only require the token for that backend (i.e. `TEST_JOB_SERVER_TOKEN`)
> Sync multiple backends

- jobrunner/agent/main.py
- jobrunner/controller/main.py
- tests/agent/test_agent.py
- tests/controller/test_main.py
Because we are migrating between systems and the code is under heavy development we anticipate hitting errors much more often than we have historically. But we also anticipate fixing these rapidly and so it's much better from the user's perspective if these errors don't cause their jobs to fail.
We eventually expect to move back to treating at least some errors as permanent failures of the job and so, to avoid either removing or leaving untested these code paths, we add a mechanism for simulating a permanent failure in the test suite. 
Closes #930
> Consider all platform errors as transient for the time being

- jobrunner/agent/tracing.py
- jobrunner/controller/main.py
- jobrunner/executors/local.py
- tests/controller/test_main.py
- tests/test_local_executor.py
Ensure that job metadata always has all expected keys present.
They maybe Falsey or have default values in some cases, like when reading
metadata.json generated by older version of job-runner, but they will always be
present.
The goal is to always be able to assume presence and use `metadata["key"]`
rather than `metadata.get(key)`, thus simplifying usage.
I chose to just deal with the expected issues we have with the migration to the split, in that only some things will be missing from old version of written metadata.json, which were only written on a successful finalize. I anticipate we'll make further changes to this later, I think we can do a better job of typing and defining job metadata with some refactoring
Fixes #931
> Robust metadata

- jobrunner/cli/kill_job.py
- jobrunner/cli/prepare_for_reboot.py
- jobrunner/cli/retry_job.py
- tests/cli/test_kill_job.py
- tests/cli/test_retry_job.py
Where appropriate, filter jobs by backend in the CLI commands. This currently uses the agent's BACKEND as a default, in preparations for at least some of these commands being run by the controller outside of the backend itself. It does not yet do the work of splitting the commands between agent and controller and making them runnable by the controller only (via tasks) - see #929 .
Fixes #927
> Filter jobs by backend in cli commands

- jobrunner/controller/main.py
I think this means that cancellation currently works OK from the user's point of view (because we deactivate the RUNJOB task) but we never actually stop the container or clean it up because the task to do so won't be picked up by the agent.
> Fix missing `backend` on CANCELJOB task

- jobrunner/controller/main.py
This restores behaviour which we lost in the agent/controller split. It allows us to provide confirmation to the user that their job is actually still running.
See:
https://bennettoxford.slack.com/archives/C069YDR4NCA/p1746626176239809
> Regularly update the timestamps of running jobs

- jobrunner/cli/controller/prepare_for_reboot.py
- jobrunner/controller/main.py
- tests/cli/controller/test_prepare_for_reboot.py
- tests/controller/test_main.py
Fixes #957 
I decided not to add a new KILLJOB task, as CANCELJOB does everything that's needed, and the job status has the information that the job is waiting on reboot (and cancel_job is used for killing jobs in db maintence already)
Prepare for reboot now creates CANCELJOB tasks. It checks that the backend is paused before doing anything, as we need the agent to be running in order to pick up the cancel tasks, but we don't want pending ones to be started.
Also adds a --status option so we can check if we're safe to do the actual reboot (i.e. no running jobs or active cancel tasks)
> Update prepare for reboot CLI command

- jobrunner/agent/task_api.py
- jobrunner/controller/task_api.py
This is a small hack to ensure that the controller always receives the results of DBSTATUS tasks before the results of RUNJOB tasks so that if the jobs have failed because we've just entered database maintenance then the controller will handle the failures correctly.
This not the proper fix, but it's cheap to do, has little downside and may help.
Closes #893
> Always return DBSTATUS tasks first from controller

- jobrunner/cli/agent/kill_task.py
- tests/cli/agent/test_kill_task.py
Allows for partial job-id matching to kill running tasks for jobs. This just kills the docker container and cleans up; on the next agent loop, the task will still be active, but as there's no container, the agent will prepare it again and retry.
Fixes #959
> Add a kill_task agent cli command

- .github/workflows/tests.yml
- controller_app/settings.py
- docker/Dockerfile
- docker/dependencies.txt
- docker/docker-compose.yaml
- docker/justfile
- docker/scripts/agent.sh
- docker/scripts/controller.sh
- jobrunner/agent/task_api.py
- tests/agent/test_task_api.py
This updates the Dockerfile to build a single image which we expect to be invoked in two separate ways: as agent and as controller. For each role we add an appropriate entrypoint script.
The controller script actually runs two processes: a Django web process in the foreground and the controller loop in the background. The background process is managed by the `run-one-constantly` tool following the same approach as used in Airlock.
The functional test is updated to use two separate containers communicating over HTTP so as to mimic production. And this test is now included in the CI checks.
Partially addresses #967
> Test agent/controller deployment as two separate containers

- controller_app/views.py
- gunicorn.conf.py
- jobrunner/tracing.py
- manage.py
- pyproject.toml
- requirements.prod.txt
- tests/controller_app/test_views.py
Adds the auto-instrumentation and setup in gunicorn.conf.py and manage.py in the same way as Airlock.
Just traces backend and task id from the views for now.
This is going into main, so it should get applied to the dokku4 app, but won't actually trace anything there yet because it doesn't have `OTEL_EXPORTER_OTLP_HEADERS` set.
Fixes #989
> Add telemetry for the django app

- controller_app/views.py
I didn't add this before because more recent otel updates already do type validation, but we'll still want it to cast invalid types to str.
> Use set_span_attributes for django app tracing

- jobrunner/controller/main.py
- jobrunner/models.py
- tests/controller/test_main.py
- tests/test_integration.py
- tests/test_models.py
This was slightly more complex than I initially thought, because I didn't want to set jobs to `PREPARING` when the task is created, because we want `status_code` to reflect the agent stage, and not change to to `PREPARING` until the agent says it is. But `set_code()` still needs to receive a new code when the task is created, so I've added a new `INITIATED` state.
Fixes #986
> Store fine-grained agent stage in the controller

- controller_app/settings.py
None of this was used, but it triggered unapplied migration warnings.
Closes #874
> Remove all Django config which required a database

- jobrunner/agent/main.py
- tests/agent/test_agent.py
This means we will move on to the next job, rather than restarting the
whole loop again.
We still track if any errors are produced, and raise at the end of loop
to be restarted by systemd.
Fixes: #1000
> Handle exceptions in the agent loop, rather than raising

- controller_app/views.py
- jobrunner/agent/main.py
- jobrunner/agent/task_api.py
- jobrunner/controller/main.py
- jobrunner/controller/task_api.py
- jobrunner/models.py
- tests/agent/stubs.py
- tests/agent/test_agent.py
- tests/agent/test_main.py
- tests/agent/test_task_api.py
- tests/controller_app/test_views.py
- tests/test_integration.py
Fixes #1009 
The state change timestamp is computed and stored already on JobStatus, so in `update_job_task` we now send it to `update_controller`.  (It can also be None, for non-job-related tasks - i.e. DBSTATUS)
For running jobs, the controller uses the task's agent_timestamp_ns (if available) instead of the current time to set the job's status_code_updated_at timestamp and for tracing.
> Send state change timestamps from agent to controller

- tests/agent/stubs.py
- tests/cli/controller/test_prepare_for_reboot.py
- tests/controller_app/test_views.py
- tests/factories.py
Makes canceljob_db_task_factory consistent with runjob_db_task_factory, which allows us to more easily make multiple tasks for the same job, and also simplifies some tests that need to make an inactive cancel task.
> Make canceljob_db_task_factory take an optional job

- jobrunner/lib/database.py
- tests/conftest.py
- tests/lib/test_database.py
Tests that need a database use the `db` fixture, which patches the DATABASE_FILE config to a temporary filepath. If you write a test and forget to add the db fixture, but you have a local db, the test will pass, but it'll use your (real) local db. This means that it (a) messes with your local environment and (b) makes the test fail in CI only, where there's no local db for it to use.
This adds an autouse fixture that always sets the DATABASE_FILE config variable to a temporary path. If a test attempts to use the database without the db fixture, it will fail because the db fixture runs the actual database setup, which we only want to do if it's required.
> Make tests error if they need the db fixture

- jobrunner/executors/local.py
- tests/test_local_executor.py
The previous wording ("job cancelled by user") was confusing, because a CANCELJOB task receive by the agent is not necessarily a result of a job that has been cancelled by a user. It can also be a job that's been cancelled by db maintenance, or by a prepare-for-reboot.
If a user cancels a job, the Job will have the cancelled flag set in the db, and the controller will [mark it as failed with the "Cancelled by user" status message](https://github.com/opensafely-core/job-runner/blob/afe1e4219284dab1ebfef3538774a41cf0e804b3/jobrunner/controller/main.py#L174).
So if we're displaying a cancellation message from the job metadata, it will be for a job that's been cancelled by some non-user requested means. (Note that for a user-cancelled job, the job metadata will still record "cancelled by …
> Update job metadata message for cancelled jobs

- jobrunner/agent/main.py
- tests/agent/test_agent.py
A job in the PREPARED state has no container yet, but it does have a volume (which is how get_status() identifies it as PREPARED. https://github.com/opensafely-core/job-runner/blob/4df192219032451622ce99818402a20abc8e21ca/jobrunner/executors/local.py#L305
We therefore also need to run cleanup after cancelling  a job that is PREPARED; cleanup will try to delete the container, but it ignores errors if there's no container to remove, and it will delete the volume.
> Run cleanup() for cancelled jobs in the PREPARED stage

- jobrunner/agent/metrics.py
- jobrunner/agent/tracing.py
- jobrunner/cli/controller/add_job.py
- jobrunner/controller/main.py
- jobrunner/models.py
- jobrunner/queries.py
- jobrunner/schema.py
- jobrunner/tracing.py
- tests/agent/test_metrics.py
- tests/agent/test_tracing.py
- tests/controller_app/test_views.py
- tests/lib/test_log_utils.py
- tests/test_queries.py
Fixes #987 
The ticket mentions adding an attribute dict to AgentTask, which the controller populates with any key-value pairs. Since the main ones that we want to add at the moment are only available on a SavedJobRequest, I've added the attribute dict to the Task model so it will be stored in the db.  Otherwise it will need to query SavedJobRequest for every task, every time the agent and metrics loops call get_active_tasks().
> Add attributes to agent task for telemetry

- dotenv-sample
- jobrunner/agent/task_api.py
- jobrunner/config/agent.py
- tests/agent/conftest.py
- tests/agent/test_task_api.py
- tests/controller/test_main.py
- tests/test_integration.py
When doing some config cleanup I found this confusing and I think it would be better to be consistent here.
I've already added the relevant env vars to the TPP and Test backends so this should be safe to deploy.
> Rename `JOB_SERVER_TOKEN` to `TASK_API_TOKEN` in agent

- gunicorn.conf.py
They are not necessary
- nginx on dokku4 has access logs
- we have otel traces
- its noisy, hides more useful services logs
- completely different format, thats a bit hard to usefuly change
> Disable gunicorn access logs

- jobrunner/controller/main.py
- tests/controller/test_main.py
A bug in the previous implementation of using set_code with a timestamp meant that we actually never set the timestamp to the agent-provided timestamp for running jobs.  However, we still don't want to _always_ set the timestamp to the agent-provided timestamp, because then we'd never change the updated_at time for a job whose status code hadn't changed.
This fixes the bug with the positional/keyword args, and also updaes set_code() so that we use the agent-provided task timestamp only when a status code has changed. If it hasn't changed, we use the current time instead.
(Note that we could perhaps add a field to the Task to record the time it was updated in `task_api.handle_task_update()`, and use that for running jobs. That would be more accurate in recording the time the _agent_ last …
> Fix bug in update timestamps

- jobrunner/controller/main.py
- jobrunner/create_or_update_jobs.py
- jobrunner/tracing.py
- tests/controller/test_main.py
- tests/test_create_or_update_jobs.py
- tests/test_tracing.py
Previously, all failed jobs were marked errors in the telemetry, by
setting the span status to ERROR. We are really only interested in
internal or platform errors being marked that way, as there are many
reasons jobs fail that are expected and normal
Addded a succeeded attribute to make it easier to filter on failed jobs
in honeycomb.
Fixes #982
> Only mark actual errors as errors in telemetry

- jobrunner/config/controller.py
- jobrunner/controller/main.py
- tests/controller/test_main.py
Hardcoding the list like this is obviously not particularly lovely, but there's precendent for it (e.g. in [job-server][1]) and it has certain advantages in forcing everything through code review and leaving an audit trail.
The number of repos is expected to remain small, and the feature as a whole has a limited lifespan: NOD have agreed that after a period of testing, event-level data access needs to be either made generally available or canned completely.
[1]: https://github.com/opensafely-core/job-server/pull/3558
> Enable specific repos to use ehrQL's event level data

- agent/cli/ehrql_telemetry.py
- tests/agent/cli/test_ehrql_telemetry.py
This adds an agent CLI command, which can be executed in the deployed environment with:
```
just ehrql_telemetry DATASET_NAME JOB_SPECIFIER
```
This will read the job's log file, parse out the relevant events, and push them as backdated otel records into the specified Honeycomb dataset. 
`DATASET_NAME` can be chosen pretty much arbitrarily as long as:
* you avoid using one of our existing service names like `rap-controller`;
* you use a consistent dataset name when processing all the jobs you want to analyse.
`JOB_SPECIFIER` can either be a job ID or a path to a job's log directory.
For more detail on why we are using this approach see the below document:
https://docs.google.com/document/d/1EXdQNSOUOvbx42JUw952GvCwh87C4sLbYlLkMQqe4EI/
> Add agent cli command for emitting ehrQL telemetry

- DEVELOPERS.md
- Mention you probably want to migrate the database first (at least, if I run the controller first in a fresh checkout, I get in a bad state).
- Mention getting the docker images early as it's more convenient to just grab them all once rather than when the agent falls over.
- Add the command to clone the remote repo for the local repo example as it's convenient to have it it hand when following this.
- Tweak some language to make it slightly clearer which database is being referred to.
Combining a few in one commit for expediency.
> Getting started docs tweaks

- controller/main.py
- controller/permissions/datasets.py
- tests/controller/test_main.py
The initial permissions configuration is taken from the current yaml
config in opensafely cli, with a number of changes made to match the way
t1oo's work in job-server, which is where we intended this config to
live long term.
- key by project rather than repo
- use project slug rather than number, as job-runner doesn't know that.
- use python rather than yaml
Have used the names of the tables as defined in opensafely-cli for now,
we may want to change the string values once we know what they will be.
The plumbing is fairly straightforward, it just sets a job env var with
the values of any permitted tables as a comma separate string for ehrql
to parse.
Lots of design discussion here: https://bennettoxford.slack.com/archives/C069YDR4NCA/p1752683993581859
> Add initial configuration and plumbing for restricted datasets

- controller/create_or_update_jobs.py
This is more time-efficient.
The list comprehension in `get_new_jobs_to_run` is almost all of the execution time of `get_latest_jobs_for_actions_in_project`. Repeatedly checking if list items are present in another list requires repeatedly traversing the other list and doing many comparison operations.
That approach grew with the product of the length of the lists (roughly quadratic). This approach grows additively with the lengths as each lookup takes constant time (roughly linear overall).
In local testing, this reduces the `get_new_jobs_to_run` execution time with 2k jobs from 5.2s to 0.485s (90% speedup).
Relates to #1105. Don't merge until telemetry is in place and has run for a bit.
> Use lookup table to find new jobs.

- dotenv-sample
In a local environment running job-server and the rap controller together, <BACKEND>_CLIENT_TOKENS must match the value of job-server's RAP_API_TOKEN in order for job-server to be able to authenticate with the controller.
> Update dotenv-sample client token to match job-server

- controller/create_or_update_jobs.py
Spotted when analysing jobs data for platform insights.
> Fix typo in NothingToDoError message

- controller/permissions/datasets.py
This removes and clarifies some of the autogenerated permissions.
I went through the list, and found any issues, and resolved them. There were
multiple different reasons for removal, as noted in each commit. I compared
the config to the permissions recorded in the projects spreadsheet, and in
jobs.opensafely.org, and talking to Alex for appointments permissions.
The general principle was to fail closed. That is, if in doubt, remove the
permission - we can always easily re-add it if needed.
Fixes #1113
> Review dataset permissions

- controller/webapp/settings.py
- tests/agent/test_agent.py
- tests/common/lib/test_service_utils.py
Format matches the agent/controller/sync format (see `common/lib/log_utils.py`)
I've added basic loggers (django, guinicorn and the webapp); open to suggestions about what logging config we actually want though
Fixes #1156
> Add logging config for the webapp

- controller/webapp/views/rap_views.py
* The db schema on job-server does not allow a null value for the
run_command, so by returning the empty string we can make the
client code a little simpler
* this is also consistent what the previous run loop implementation
did - for reasons which I had not got to the bottom of
* the api spec does say that this field is a string, so `None` isn't ideal
> Return run_command as '' instead of None for run_all jobs

- controller/create_or_update_jobs.py
- tests/controller/test_create_or_update_jobs.py
- tests/test_integration.py
Towards RAP API v2. Now that the Job Server UI can be used to cancel `test` jobs via `webapp`, the synchronisation loop does not need to. This allows us to test the RAP API cancel without any use of the loop, end to end. 
If this works well we will eventually do the same for all backends, deleting the code path.
Partially fixes https://github.com/opensafely-core/job-runner/issues/1167
> Stop `sync` cancelling jobs for `test` backend.

- controller/main.py
- tests/controller/test_main.py
This is instead of a comma-separated list. At present permissions are just lists of strings but we want to leave open the possibility of passing more complex structured data. Plus, using a "real" encoding seems better for this purpose than DIYing it, however simple the current implementation is.
We also include Event Level Data access in the permissions list, as well as setting the appropriate environment variable. Once ehrQL is updated we can drop the extra environment variable which gives us a much cleaner API.
> Use JSON to encode ehrQL permissions

- .github/workflows/tests.yml
We initially had these in place (alongside Windows tests) because the old codebase needed to work on users' machines. During the Agent/Controller split work we dropped the Windows tests but kept macOS because at least one developer was using macOS locally.
This is no longer the case and, due to some current flakiness with Github's macOS runners, it doesn't seem worth the cost to keep these in place.
See related Slack thread:
https://bennettoxford.slack.com/archives/C069YDR4NCA/p1759314821692029
> Remove macOS tests from CI

- controller/config.py
Where we can safely give the user more information about why their ehrQL job failed we should do so. See:
* https://github.com/opensafely-core/ehrql/pull/2543
> Handle some more specific ehrQL exit codes

- controller/main.py
- tests/controller/test_main.py
As the below PR is now merged and deployed this env var is no longer read:
* https://github.com/opensafely-core/ehrql/pull/2552
> Remove unused env var from ehrQL jobs
