runner/exceptions.py, tests/test_runner.py
=> Allow our custom exceptions to be pickled

jobrunner/job.py, jobrunner/main.py, jobrunner/project.py, jobrunner/server_interaction.py, jobrunner/utils.py, tests/common.py, tests/fixtures/invalid_project_1/project.yaml, tests/fixtures/simple_project_1/project.yaml, tests/fixtures/simple_project_2/project.yaml, tests/test_job.py, tests/test_project.py
Adds the ability to use globs and subdirectories in project output paths.
=> Flexible output paths

jobrunner/main.py
=> fix: don't exit on HTTP errors

Dockerfile, docker-compose.yaml, dotenv-sample, jobrunner/job.py, jobrunner/main.py, jobrunner/project.py, jobrunner/server_interaction.py
A raggle-taggle assortment of fixes I've had to make to fulfil the obligation I've set myself to get snotty noses run by the end of the week.
=> Misc fixes

jobrunner/job.py
=> fix: use posixpath where we plan to run in linux container

jobrunner/project.py
@bloodearnest, do you think you could deploy this after merging? I'll prob be in meetings...
=> Add python runner

jobrunner/config.py, jobrunner/sync.py, tests/test_integration.py, tests/test_sync.py
This is a grab bag of small tweaks to match job-server's v2 API interface.  Hopefully each commit is explanatory enough!
=> Job Server Compatibility Fixes

.github/workflows/build_and_publish.yaml
Note: this is tagged feat in order to explicitly push a new image when merging.
=> feat: image publish to ghcr.io

jobrunner/project.py, tests/test_project.py
This reverts commit 1649bd30cc66fc645d77cd406e882c05cac7981f.
=> feat: Revert "make the default docker url the old registry path"

jobrunner/project.py, tests/test_project.py
This reverts commit 329ca953ed3999c0e715d744276108b9de25b97e.
=> feat: make the default docker url the old registry path

requirements.dev.txt, requirements.txt
This was mainly done so that I can bump the major version which I tried
to do earlier but didn't work because it didn't pull the PR description
into the merge commit message as I expected.
BREAKING CHANGE: Version 2.0 please
=> feat: Update requirements

jobrunner/local_run.py
This is done so that existing Github Actions tests run as-is, even
though they're authenticating with the old Docker registry.
Should be removed as soon as we update the actions.
=> fix: Temporary workaround for Docker auth issues in CI

jobrunner/local_run.py
This allows us to give more helpful error message to the user.
Closes #110
=> fix: Check Docker installed and running before doing anything

jobrunner/log_utils.py
This is enabled by setting the `LOG_TIMESTAMPS` environment variable to
a non-empty value. In general we'd expect this to be handled by whatever
is runnning us as a service, but that isn't always possible.
=> fix: Add the option to include timestamps in logs

jobrunner/run.py
I meant to log these messages about once every 10 minutes, not every 9
out 10 minutes.
=> fix: Fix silly logging error

jobrunner/sync.py
Couple of small "optimisations", most for local dev when debugging API interactions, although the removal of empty job updates saves a bit of traffic in production.
=> Usage Optimisations

jobrunner/service.py
This is done before we import config, so the env vars are set when it imports
=> feat: parse .env file on module import.

jobrunner/local_run.py, jobrunner/log_utils.py, jobrunner/manage_jobs.py, jobrunner/models.py, jobrunner/service.py, tests/test_local_run.py, tests/test_log_utils.py
Also includes some black changes
=> fix: respect log context again and fix log status_code filtering

jobrunner/kill_job.py, jobrunner/retry_job.py
=> fix: Fix silly bounds check error

playbooks/TPP.md
Have stuck these in the TPP playbook for now along with everything else.
Later we should restructure these as many things will be common.
=> docs: Add brief notes on stracing

jobrunner/docker.py, jobrunner/manage_jobs.py
Aborting a `docker cp` into a container at the wrong time can leave the
container in a completely broken state where any attempt to interact
with or even remove it will just hang, see:
https://github.com/docker/for-mac/issues/4491
This means we can end up with jobs where any attempt to start them (by
copying in code from git) causes the job-runner to completely lock up.
To avoid this we use a timeout (60 seconds, which should be more than
enough to copy in a few megabytes of code). The exception this triggers
will cause the job to fail with an "internal error" message, which will
then stop it blocking other jobs. It's important that we don't use a
subclass of JobError here because such errors are regarded as "clean"
exits and cause the runner to try to remove the container, which would …
=> fix: Work around containers in broken state

playbooks/TPP.md
This adds docs on how to update the job-runner on the TPP server.
=> docs: update runner

jobrunner/manage_jobs.py, tests/test_integration.py
The workspace.json file contains metadata that can be used by the level 4
redaction process.
=> feat: include a workspace metadata in medium_privacy outputs.

jobrunner/create_or_update_jobs.py
This will allow the job-server to handle these differently in the UI and
display more helpful error messages.
This is a bit hacky and adds complexity to some of the UI code, but it
keeps complexity out of the sync protocol and so is a worthwhile
tradeoff.
=> fix: Use a dedicated action name for "error" jobs

jobrunner/config.py, jobrunner/local_run.py, jobrunner/manage_jobs.py, tests/test_config.py
This adds a `--debug` flag to the local_run command which leaves all
Docker containers and volumes in place for debugging purposes.
=> feat: Add `--debug` flag to disable cleanup

jobrunner/local_run.py
This is useful in CI settings.
=> fix: add option for local_run to emit timestamps

jobrunner/local_run.py, tests/test_local_run.py
Added a test to ensure local_run cli args work.
=> fix: timestamps cli arg definition was broken

.gitignore, Makefile, jobrunner/add_job.py, jobrunner/kill_job.py, jobrunner/local_run.py, jobrunner/retry_job.py, setup.py
This allows use to invoke them more easily in production, as they are on the path.
=> fix: add subcommand entrypoints

jobrunner/extract_stats.py
This is quick and dirty, but I've done something like this enough times
now that it's worth scripting up.
=> feat: Add script to extract usage stats

README.md
Some minor updates to the README while checking the instructions for developers all work OK, as per https://github.com/opensafely-core/project-tidy-up/issues/18
=> docs: Minor updates to README

.github/workflows/build_and_publish.yaml
=> chore: Support using "main" branch in workflows

jobrunner/docker.py
Shelling out to the Docker client on Windows sometimes hangs
indefinitely (for no obvious reason that we can determine). To prevent
this locking up the entire process we use a large-ish default timeout on
almost all calls to Docker.
The exceptions are copying files and pulling images which we expect to
sometimes take a long time. Pulling images is only done locally at the
moment in any case so we don't need to worry too much about that.
There's no simple way I can think of to distinguish a slow copy of a
large file from a broken call to Docker, so we'll just have to live with
that risk for now.
=> Use timeouts everywhere when interacting with Docker

playbooks/tpp-backend.md
There's a further piece of work here which is separating out the
TPP-specific stuff from the generic cross-backend stuff, but one thing
at a time.
=> docs: Update TPP playbook

tests/test_project.py
I wrote these to fix a bug that turned out to be elsewhere. However, I think they're useful.
=> Test config

jobrunner/log_utils.py, jobrunner/run.py
This adds support for a `DEBUG_LOG_FILE` environment variable to which we log at level DEBUG while leaving the primary logs at their default log level. This is necessary because DEBUG logging is extremely noisy and we want to avoid polluting the primary logs.
We also add extra `log.debug()` calls around critical points in the run loop to try to determine where it is locking up.
=> Add debug logging to `run` loop

jobrunner/docker.py, jobrunner/manage_jobs.py, jobrunner/record_stats.py, jobrunner/system_stats.py
The real solution here is an intelligent scheduler which knows not to
start jobs until there's enough space for them to run. But this should
improve the situation until that comes along.
=> Return specific error for disk space issues

docker/Dockerfile, docker/Makefile, docker/docker-compose.yaml, jobrunner/cli/local_run.py, jobrunner/config.py, tests/conftest.py, tests/test_service.py
- chore: fix docker-compose environment for WORK_DIR
- chore: make docker/Makefile able to run the prod docker image more easily
=> fix work dir env

jobrunner/lib/docker.py, tests/lib/test_docker.py
In prod we saw instances subprocess_run returning docker errors with
stderr==None, which blew up the previous error handling, and introduced
all kinds of bugs in the error handling.
This change makes the except clause much more robust when handling the
output of a failed docker command.
=> fix: handle docker error reponse more robustly

jobrunner/executors/local.py, jobrunner/lib/docker.py
run the management containers for the duration, and add labels to management containers and and volumes
=> run manager containers

jobrunner/executors/local.py, jobrunner/job_executor.py, jobrunner/run.py, tests/test_local_executor.py, tests/test_run.py
=> fix: more helpful warning if killed by 137

.github/workflows/tests.yml, DEVELOPERS.md, jobrunner/cli/local_run.py, jobrunner/reusable_actions.py, setup.py
This sets the minimum version of Python we support to 3.8.
=> Switch to 3.8 as the base Python version

.gitignore, jobrunner/lib/docker.py, tests/lib/test_docker.py
Copy to a tempfile and rename, making the filesystem view atomic.
This is going to be useful for our upcoming migration, but also is
a good idea anyway.
=> feat: more robust copy from volume

jobrunner/manage_jobs.py, jobrunner/project.py, jobrunner/run.py, tests/test_project.py
Like the generate cohort command, this requires access to the database.
It's a custom command that uses some custom SQL to quickly query the
database for OS Interactive
=> Add generate codelist report

jobrunner/run.py, tests/test_run.py
This mode will a) kill any running db jobs and b) prevent
pending db jobs from starting.
Currently, it can be set manually by running
`python -m jobrunner.cli.flags set mode=db-maintenance`
Note: this never has effect in local_run scenarios as it uses the dummy
db - it only changes behaviour when there is a real database configured.
=> fix: add db maintenance mode.

jobrunner/config.py, jobrunner/service.py, jobrunner/sync.py, justfile, requirements.dev.txt, tests/conftest.py, tests/test_service.py
- refactor: add a start_thread method in service.py
- chore: update dev tooling due to broken pip/pip-tools
- chore: add fixture for mocking subrocess.run
- feat: support detecting and activating maintenance mode
- fix: communicate current mode in job-server requests
=> db maintenance auto

jobrunner/service.py, tests/test_service.py
Also, log when we're running it and the outcome.
=> fix: pass env var to maintenance command

jobrunner/executors/local.py
This way, db jobs can appropriately marked as OOM killed.
Also, allow general error code messages to apply to db jobs too, not
just the db specific ones.
=> fix: handle OOMKilled first, before checking for known error codes.

.github/workflows/build_and_publish.yaml, docker/justfile
Also clean up some GHA debugging that accidentally got committed.
=> chore: fix the post-merge publish workflow

jobrunner/run.py, tests/test_run.py
This was accidentally removed in executor API refactor. See #459 for
more details.
=> fix: re-introduce MAX_WORKERS check

jobrunner/cli/local_run.py, tests/cli/test_local_run.py
You can now control concurrency, cpu, and memory limits from the cli.
=> feat: add cli args to control job execution.

jobrunner/lib/database.py, jobrunner/tracing.py, justfile
- fix: migration import and add just command
- fix: keep dist-info dirs in wheels, as some packages introspect them
- fix: really skip jobs that are untraceable
=> deployment fixes

jobrunner/tracing.py, tests/test_create_or_update_jobs.py, tests/test_run.py, tests/test_tracing.py
- better classification of which spans are state transistions or not
- fix: make the root span duration last the whole job.
=> root span duration

jobrunner/tracing.py, tests/test_tracing.py
We have seen some errors in production about some span attribute values
being None, but the logs do not say which attributes.
This change ensures all attributes are valid types. If they are not, it
coverts to string, and logs so we can find out where the bad attribute
is comming from.
=> fix: ensure trace attributes are valid types

DEVELOPERS.md
* fixes https://github.com/opensafely-core/job-runner/issues/486 (well, is the final thing to fix that ticket!)
=> docs: add state flow diagram to dev docs

jobrunner/sync.py
This extends the notion of an active JobRequest to include not only all those which job-server considers active but also any which job-runner still considers active.
Under normal circumstances this change makes no difference as the former is always a superset of the latter. But where a previously inactive job has become active again (because of manual intervention by an admin) then it's possible that job-runner can have active jobs which job-server doesn't know about.
This is not a practice we want to encourage (and it will have other unwanted effects e.g. with respect to metrics gathering) but nevertheless it does happen sometimes and its better if we can robustly handle this and always move towards stabilising on a consistent state between job-runner and job-server.
=> fix: Tweak the sync protocol to make it more robust

jobrunner/run.py, tests/test_run.py
Linked to: https://github.com/opensafely-core/job-server/pull/2399
Refs: https://github.com/opensafely-core/job-server/issues/2308
=> Improve message for jobs exiting with an error

jobrunner/cli/kill_job.py, jobrunner/executors/local.py, tests/cli/test_kill_job.py
=>  fix: kill_job preserves job logs

.github/workflows/tests.yml, jobrunner/config.py, jobrunner/executors/local.py, jobrunner/job_executor.py, jobrunner/run.py, jobrunner/tracing.py, tests/factories.py, tests/test_config.py, tests/test_integration.py, tests/test_local_executor.py, tests/test_tracing.py
- fix: better tracing of JobResults
- fix: tag otel spans with the version of job-runner that generated them
- fix: add docker label metadata to spans
=> more trace metadata

jobrunner/run.py, tests/cli/test_prepare_for_reboot.py, tests/conftest.py, tests/test_create_or_update_jobs.py, tests/test_integration.py, tests/test_local_executor.py, tests/test_record_stats.py, tests/test_run.py, tests/test_tracing.py
- get_spans() test helper can now filter by tracer name
- attempt to reducing chance of flaky oomkiller test
- chore: add loop tracing
=> loop metrics

jobrunner/executors/local.py, jobrunner/executors/volumes.py, jobrunner/job_executor.py, jobrunner/lib/docker.py, jobrunner/run.py, tests/factories.py, tests/test_local_executor.py, tests/test_run.py, tests/test_tracing.py
- fix: add timestamp to JobStatus
- fix: add missings state trace spans with timings
=> fix trace timestamps

jobrunner/run.py, tests/factories.py, tests/test_run.py, tests/test_tracing.py
This reverts commit 542232d26b1134552b478e234213c34a19909d43.
=> Revert "fix: add missings state trace spans with timings"

jobrunner/cli/prepare_for_reboot.py, jobrunner/executors/local.py, jobrunner/lib/__init__.py, jobrunner/models.py, jobrunner/run.py, tests/factories.py, tests/test_local_executor.py, tests/test_run.py
- fix: ensure int timestamp in negative duration handling
- refactor: subsume set_state into set_code
- feat: make run loop handle synchronous operations
=> fix timings

jobrunner/create_or_update_jobs.py, tests/test_create_or_update_jobs.py
* experimental instrumentation to explore what this block is doing in production
* to be reverted if trace volumes get out of hand and/or investigation is complete
=> feat: instrument assert_new_jobs_created

jobrunner/lib/yaml_utils.py, justfile, pyproject.toml, requirements.prod.txt
ruyaml is a maintained fork of ruamel.yaml without a C dependency.
=> fix: update pipeline and switch to ruyaml

jobrunner/executors/volumes.py, tests/test_local_executor.py
- chore: refactor local executor test
- fix: handle BindMount directory already existing
=> bind mount fixes

tests/factories.py, tests/test_local_executor.py, tests/test_run.py
* clarify some states
* rename some misnamed vars
* add some more scenarios
=> chore: enhance tests

jobrunner/executors/local.py
* I did a lot of this in https://github.com/opensafely-core/job-runner/pull/593 , but apparently I missed the most important file that I had mostly been working on that caused me to do #593 in the first place.
=> chore: improve some more var naming

jobrunner/run.py
- only run db, except for OSI worksapces
- hidden behind envvar for control
=> Add temporary fix for urgent windows

scripts/archive.sh
* this has been done on the production TPP server, this updates the script to match
* fixes https://github.com/opensafely-core/sysadmin/issues/116
=> fix: move mountpoint to $HIGH_PRIVACY_BASE

tests/factories.py
this one feels a bit flat-footed / overly-verbose, but it’s the kind of slightly-more-stuff-that-you-have-to-hold-in-your-head that made it a lot slower for me getting started with this codebase…
=> chore: make explicit some state vars that are ExecutorStates

DEVELOPERS.md
This adds a checklist, with backend-specific instructrions, for deploying.
=> Add a checklist for deploying

DEVELOPERS.md
I forgot that markdown lists get run together regardless of newlines inbetween… silly. me.
=> Break up the two lists

jobrunner/config.py, jobrunner/executors/local.py, jobrunner/job_executor.py, jobrunner/run.py, tests/test_local_executor.py
- Rename leve4 file size config
- Add more l4 file limits
=> more l4 limits

jobrunner/config.py, jobrunner/executors/local.py, jobrunner/run.py, tests/test_local_executor.py, tests/test_run.py
- Log excluded files rather than in status_message
- Allow .log files on level 4
=> level 4 check fixes

jobrunner/actions.py, pyproject.toml, requirements.prod.txt, tests/lib/test_lru_dict.py
Reverts opensafely-core/job-runner#635
=> Revert "Bump pipeline to v2023.08.21.134839 (pydantic v2)"

.pre-commit-config.yaml, pyproject.toml, requirements.dev.txt, requirements.prod.txt
Also had to bump isort for pre-commit hooks to work
=> Upgrade os-pipeline to v2023.11.03.163048

jobrunner/cli/kill_job.py, jobrunner/executors/local.py
=> Add status_message to job logs

jobrunner/record_stats.py, tests/test_local_executor.py, tests/test_record_stats.py
The cumsum was really quite large measuring in bytes.
=> Measure aggegate memory usage in mb.

jobrunner/sync.py, tests/test_sync.py
=> Expose requires_db in job status API

jobrunner/config.py, jobrunner/executors/local.py, jobrunner/job_executor.py, jobrunner/run.py, tests/test_local_executor.py, tests/test_logging_executor.py
Fixes #726 
Accompanying [docs PR](https://github.com/opensafely/documentation/pull/1501)
=> Prevent large CSV files from being copied to level 4

jobrunner/cli/manifests.py, jobrunner/executors/local.py, jobrunner/lib/database.py
- **Backport production tweaks to backfill scripts**
- **Enforce wal mode**
=> fixes from backfill

docker/justfile, requirements.dev.in, requirements.dev.txt
pytest-freezegun is no longer actively maintained and has been moved into the main pytest-dev org as pytest-freezer
https://github.com/pytest-dev/pytest-freezer
=> Replace pytest-freezegun with pytest-freezer

.github/workflows/tests.yml, requirements.dev.txt
* hoping this will fix the compiling from source issue that was preventing @Providence-o from installing pyyaml locally on Apple Silicon
* https://github.com/yaml/pyyaml/issues/736
* use macos-14 GHA runner
=> Upgrade to pyyaml 6.0.1

justfile
No longer needed now we deploy with docker
=> Remove update-wheels command

jobrunner/executors/local.py, jobrunner/job_executor.py, tests/test_local_executor.py
=> Added hint and status message to output log for 'unmatched output' errors

jobrunner/executors/local.py, tests/test_local_executor.py
=> Added new condition and test for unmatched pattern and output error

jobrunner/executors/local.py
hopefully fixes https://github.com/opensafely-core/job-runner/issues/779
=> Gracefully handle suspected race condition

justfile
The current implementation just updates the .in file, so doesn't actually get tested :facepalm:
=> Update .txt file if pipeline has changed

jobrunner/run.py, tests/test_run.py
The db-maintenance and pause modes have special handling at the top of
the handle_job method that eagerly handle those options.
This introduced a bug that job that are to be be cancelled do not get
cancelled if those modes affect them. This means that user's db jobs are
not cancelled when in db-maintenance mode, for example.
This quick fix simply protects the eager mode handling to apply only to
jobs that are not about to be cancelled, which will let the cancellation
logic proceed as normal.
This is probably not the ideal solution, but a) this is affecting users
right now with the extended db-maintenance mode and b) we are about to
completely refactor all the things, so we can live with a less than
ideal solution
Closes #766
=> fix: do not handle modes if job is to be cancelled.

docker/docker-compose.yaml, jobrunner/lib/__init__.py, jobrunner/lib/log_utils.py, jobrunner/lib/path_utils.py, jobrunner/lib/yaml_utils.py, jobrunner/models.py, jobrunner/queries.py, jobrunner/record_stats.py, jobrunner/reusable_actions.py, jobrunner/service.py, jobrunner/sync.py, jobrunner/tracing.py, pyproject.toml, tests/lib/test_github_validators.py, tests/lib/test_init.py, tests/lib/test_log_utils.py, tests/test_reusable_actions.py
First bit of #802; coverage is now at 89%
=> Get coverage to 100%

jobrunner/actions.py, jobrunner/executors/logging.py, jobrunner/job_executor.py, jobrunner/lib/docker_stats.py, jobrunner/run.py, jobrunner/tracing.py, pyproject.toml, tests/lib/test_github_validators.py
Next bit of #802 
A couple of easy-win tests and some more skipped coverage
=> Increase coverage to 90%

.github/workflows/update-dependencies.yml
Also updates the schedule to run at 4am instead of 11pm on Wed
=> Update all dependencies with update-dependencies-action

jobrunner/cli/add_job.py, jobrunner/cli/flags.py, jobrunner/cli/kill_job.py, jobrunner/cli/prepare_for_reboot.py, jobrunner/cli/retry_job.py, pyproject.toml, tests/cli/test_add_job.py, tests/cli/test_flags.py, tests/cli/test_kill_job.py, tests/cli/test_prepare_for_reboot.py, tests/cli/test_retry_job.py
The latest instalment in #802 
Add some tests and skips to get coverage to 100% for the cli code
=> Coverage for cli

jobrunner/agent/task_api.py, jobrunner/controller/task_api.py, jobrunner/job_executor.py, jobrunner/models.py, jobrunner/run.py, jobrunner/schema.py, tests/agent/test_task_api.py, tests/controller/test_task_api.py, tests/factories.py, tests/test_job_executor.py
Initial implementation of a Task API, using a new db table to communicate
between agent and controller.
This is currently only excercised by tests, but should act as a foundation for
splitting things up.
=> Inital Task API using db table

.github/workflows/build_and_publish_dev.yaml
* created a separate workflow, so @inglesp 's comment no longer applies
=> Build & push docker images for dev branch

jobrunner/agent/main.py, jobrunner/agent/task_api.py, jobrunner/executors/local.py, jobrunner/job_executor.py, jobrunner/schema.py, tests/agent/stubs.py, tests/agent/test_agent.py, tests/agent/test_task_api.py, tests/factories.py
This is a somewhat meandering set of commits that explore and end up with a minimally working agent with a single test
This was done via mobbing over multiple days with multiple drivers, so some commits are a bit messy as state was passed around.
=> Skeleton minimal mobbed agent

jobrunner/agent/main.py, jobrunner/executors/logging.py, jobrunner/lib/log_utils.py
it works when run manually with these changes
=> Minimal changes for successful run

jobrunner/agent/main.py, jobrunner/lib/log_utils.py, jobrunner/models.py, justfile
Plus a drive by typo fix and `just` commands to run agent and controller
=> Add task info to logging

jobrunner/agent/main.py, tests/agent/test_agent.py
Report any errors back to the controller and mark the task as complete. This does not yet address persisting the error information.
Also tested manually that running agent and controller with a task that raises an exception in the agent causes both agent and controller to exit, and on rerunning the errored task is picked up by the controller and marked as failed.
=> Update controller with job execution errors encountered by the agent

jobrunner/service.py
We may want to rethink our naming a bit in future, too many mains!
Note that running both agent and controller in threads is a temporary
thing - they will be moving to being independant processes soon.
This is just a quick path to being able to run them both simulataneously
using the existing machinery.
Tested manually with add job that it works
=> Switch service.py to using split agent/controller rather than run.py

.github/workflows/build_and_publish.yaml
* env interpolation didn't work, so hard-code it
=> Hardcode $IMAGE_NAME

.github/workflows/build_and_publish.yaml, README.md
These default branch names have changed, remove the old names.
=> Remove old names

jobrunner/job_executor.py
=> Drop NullExecutorAPI

jobrunner/agent/task_api.py, jobrunner/lib/database.py
Use the same sqlite config as in airlock
=> Emergency fix for db concurrency issues

jobrunner/controller/main.py
Details in linked ticket. I have confirmed locally that this fixes the locking behaviour I was previously able to reproduce.
Closes #907
=> Switch to fine-grained transactions in controller loop

jobrunner/lib/database.py, jobrunner/queries.py, tests/lib/test_database.py, tests/test_workspace_state.py
- **Add telemetry for transactions**
- **Add explicit telemetry for suspected slow function**
=> Measure transactions and slow function

jobrunner/service.py
A better fix is still being worked on
=> Add a temporary agent wrapper so we can redeploy

jobrunner/service.py
=> Add wrapper to agent_main thread

jobrunner/lib/database.py, tests/controller/test_main.py, tests/lib/test_database.py
- Add missing test that would have caught [0bbe3d9](https://github.com/opensafely-core/job-runner/commit/0bbe3d9c86af8243c3569c6db40dc9b2fc387dfb)
- Add db decoder for boolean fields
=> Add missing decoder for bools

jobrunner/service.py, tests/test_service.py
Fixes #946, with some refactoring on the way
=> Always sleep in thread wrapper

jobrunner/lib/docker_stats.py, jobrunner/models.py
- **remove unneeded backport**
- **Use cached_property now we are on 3.10**
=> remove 39 backport

jobrunner/cli/controller/add_job.py, jobrunner/cli/controller/flags.py, jobrunner/cli/controller/prepare_for_reboot.py, jobrunner/cli/controller/utils.py, tests/cli/controller/test_add_job.py, tests/cli/controller/test_flags.py, tests/cli/controller/test_prepare_for_reboot.py
=> Add required backend arg to all controller cli commands

tests/agent/stubs.py, tests/cli/controller/test_prepare_for_reboot.py, tests/controller/test_main.py, tests/factories.py
Extracted this from my spike, as it seems a worthy change.
=> RUNJOB controller test factory refactor

requirements.dev.in, requirements.dev.txt, tests/controller/test_main.py, tests/test_integration.py, tests/test_sync.py
- Minor refactor of some controller tests, to use the relocated controller logic, which will simplify the test updates needed when the agent calls an http api
- replace request_mock with responses
=> Some test updates

controller_app/views.py, dotenv-sample, jobrunner/agent/task_api.py, jobrunner/config/agent.py, jobrunner/config/controller.py, jobrunner/sync.py, tests/agent/conftest.py, tests/agent/test_task_api.py, tests/controller/test_main.py, tests/controller_app/test_views.py, tests/test_integration.py, tests/test_sync.py
=> Use job-server tokens for task HTTP API auth

jobrunner/agent/main.py, jobrunner/controller/main.py, tests/agent/test_agent.py, tests/controller/test_main.py
Adjust the way we track agent/controller exceptions in telemetry
- flip the logic from tracking transient to tracking fatal, assuming transient is the default.
- always set the attribute, to either true or false
- consolidate tracing functions in controller, which fixes a telemetry bug
Fixes #980
=> Adjust error telemetry

jobrunner/agent/tracing.py, jobrunner/executors/local.py, tests/agent/test_tracing.py
=> Fix trace attribute types

jobrunner/agent/metrics.py, jobrunner/lib/docker_stats.py, tests/agent/test_metrics.py, tests/lib/test_docker_stats.py
Fix slow docker container ls command seen in prod
Fixes #997
=> fix slow docker cmd

jobrunner/controller/main.py, jobrunner/models.py, tests/controller/test_main.py
=> Don't re-raise Exceptions when jobs return errors

controller_app/management/commands/add_job.py, controller_app/management/commands/db_maintenance.py, controller_app/management/commands/flags.py, controller_app/management/commands/migrate_controller.py, controller_app/management/commands/pause.py, controller_app/management/commands/prepare_for_reboot.py, docker/Dockerfile, docker/scripts/bashrc_addendum, docker/scripts/django_bash_completion, jobrunner/cli/controller/add_job.py, jobrunner/cli/controller/flags.py, jobrunner/cli/controller/migrate.py, jobrunner/cli/controller/prepare_for_reboot.py, justfile, manage.py, pyproject.toml, tests/controller_app/test_management.py
Fixes #1033 
Note: I've added bash completion for dev containers, but not for prod yet, because it needs a named user and we don't yet (afaik) add a custom user for the dokku app.
=> Implement the controller CLI commands as manage commands

controller_app/views.py, tests/controller_app/test_views.py
This flag will be sent to job-server in the headers (along with any other flags for that backend), to be used for recording and reporting backend downtime.
Part of #1037
=> Set a last-seen-at flag whenever a backend calls the tasks endpoint

jobrunner/cli/controller/add_job.py, jobrunner/sync.py, tests/test_sync.py
=> Remove temporary db handler

jobrunner/config/controller.py
Confirmed in Slack here:
https://bennettoxford.slack.com/archives/C068NDYALSF/p1750755722215139?thread_ts=1750668841.193319&cid=C068NDYALSF
=> Add another vaccine effectiveness repo to ELD list

DEVELOPERS.md, dotenv-sample, justfile, tests/controller/test_config.py
- Update and document some environment variables in dotenv-sample that are needed for running with a local job-server
- Run the web app on port 3000 so it doesn't conflict
- Add a couple more just commands
- Document how to run all the things
- Add a TOC to DEVELOPERS.md
=> Local setup with jobserver

dotenv-sample, manage.py
While setting up my local environment I ran into errors in `dotenv-sample` and a missing argument in `manage.py` (linked to #1093)
=> Fix issues noticed while setting up dev environment

requirements.prod.txt
https://www.djangoproject.com/weblog/2025/oct/01/security-releases/
=> fix: Upgrade django to include security fixes in 5.2.7
